unpackaged/main/default/objects/Account_Account_Relationship__c/Account_Account_Relationship__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as a Household and a Business account.</description>
    <label>Account Account Relationship</label>
    <nameField>
        <displayFormat>AAR-{0000}</displayFormat>
        <label>Account Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relationshipa</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Account Relationshipa</relationshipLabel>
    <relationshipName>Account_Account_Relationshipa</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the relationship is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Inverse_Reciprocal_Role__c.field-meta.xml
<CustomField>
    <fullName>Inverse_Reciprocal_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Inverse reciprocal role for member account relationships on the map.</description>
    <label>Inverse Role</label>
    <referenceTo>Reciprocal_Role__c</referenceTo>
    <relationshipLabel>Account Account Relationshipa (Inverse Role)</relationshipLabel>
    <relationshipName>Account_Account_Relationshipa1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Reciprocal_Role__c.field-meta.xml
<CustomField>
    <fullName>Reciprocal_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Reciprocal_Role__c for member account relationships on the map.</description>
    <label>Role</label>
    <referenceTo>Reciprocal_Role__c</referenceTo>
    <relationshipLabel>Account Account Relationshipa</relationshipLabel>
    <relationshipName>Account_Account_Relationshipa</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Account Relationship (Related Account)</relationshipLabel>
    <relationshipName>Account_Account_Relationship1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Reciprocal_Role__c/Reciprocal_Role__c.object-meta.xml
<CustomObject>
    <label>Reciprocal Role</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Reciprocal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/FscRelMemberAarExpansionTest.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-06-25
 */
@IsTest
private class FscRelMemberAarExpansionTest {
  @TestSetup
  static void setup() {
    FscDataTestDataFactory.createTreeScenario();
  }

  @IsTest
  static void getMemberAccountRelationshipsForAccount_includesIncomingRelationship() {
    FscDataTestDataFactory.TreeScenario scenario = FscDataTestDataFactory.loadTreeScenario();
    String recordTypeDeveloperName = FscDataTestDataFactory.resolveMemberRelationshipRecordTypeDeveloperName();
    if (String.isBlank(recordTypeDeveloperName)) {
      return;
    }

    Reciprocal_Role__c siblingRole = FscDataTestDataFactory.createReciprocalRoleForMemberRelationship(
      recordTypeDeveloperName,
      'Sibling',
      'Sibling'
    );
    Id recordTypeId = FscRelRecordTypeUtils.selectAccountRelationRecordTypeId(
      recordTypeDeveloperName
    );

    insert new Account_Account_Relationship__c(
      Account__c = scenario.linkedPersonAccount.Id,
      Related_Account__c = scenario.unlinkedPersonAccount.Id,
      RecordTypeId = recordTypeId,
      Reciprocal_Role__c = siblingRole.Id,
      Inverse_Reciprocal_Role__c = siblingRole.Id,
      Active__c = true
    );

    Test.startTest();
    List<FscRelHouseholdModels.TreeMemberAccountRelationship> results = FscRelHouseholdController.getMemberAccountRelationshipsForAccount(
      scenario.unlinkedPersonAccount.Id
    );
    Test.stopTest();

    System.assertEquals(1, results.size());
    System.assertEquals(
      String.valueOf(scenario.linkedPersonAccount.Id),
      results[0].relatedAccountId
    );
    System.assertEquals('Sibling', results[0].role);
  }
}