unpackaged/main/default/objects/Account_Account_Relationship__c/Account_Account_Relationship__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as a Household and a Business account.</description>
    <label>Account Account Relationship</label>
    <nameField>
        <displayFormat>AAR-{0000}</displayFormat>
        <label>Account Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relationshipa</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Account Relationship (Related Account)</relationshipLabel>
    <relationshipName>Account_Account_Relationship1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AccountAccountRelationshipTriggerHandler.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-08-19
 */
public with sharing class AccountAccountRelationshipTriggerHandler {
  public void isAfterInsert(List<Account_Account_Relationship__c> newList) {
    FscRelAccountRelationShareService.syncSharesForRelations(newList);
  }

  public void isAfterUpdate(
    List<Account_Account_Relationship__c> newList,
    Map<Id, Account_Account_Relationship__c> oldMap
  ) {
    List<Account_Account_Relationship__c> relationsToSync = new List<Account_Account_Relationship__c>();
    Set<Id> relatedAccountIds = new Set<Id>();

    for (Account_Account_Relationship__c relation : newList) {
      Account_Account_Relationship__c oldRelation = oldMap.get(relation.Id);

      if (oldRelation == null) {
        relationsToSync.add(relation);
        continue;
      }

      if (relation.Related_Account__c != oldRelation.Related_Account__c) {
        relationsToSync.add(relation);

        if (oldRelation.Related_Account__c != null) {
          relatedAccountIds.add(oldRelation.Related_Account__c);
        }
      }
    }

    FscRelAccountRelationShareService.syncSharesForRelations(relationsToSync);

    if (!relatedAccountIds.isEmpty()) {
      FscRelAccountRelationShareService.syncSharesForRelatedAccounts(
        relatedAccountIds
      );
    }
  }
}