unpackaged/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Account_Related_Product__c/Financial_Account_Related_Product__c.object-meta.xml
<CustomObject>
    <label>Related Product</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Related Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Account_Related_Product__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipName>Financial_Account_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account_Related_Product__c/fields/Flow_Interview_Id__c.field-meta.xml
<CustomField>
    <fullName>Flow_Interview_Id__c</fullName>
    <label>Flow Interview Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account_Related_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Related Products</relationshipLabel>
    <relationshipName>Financial_Account_Product1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/Flow_CreateFARPs.cls
global class Flow_CreateFARPs {

    @InvocableMethod(label='Flow_CreateFARPS' description='Pass in a Collection of Strings that are Product Ids and a collection of wizard fin accts and it will create a FARP for each fin acct.')
    global static List<FlowOutput> createFARPs(List<FlowInput> inputs){
		List<Financial_Account__c> wizFins = inputs[0].finAccts;
        List<String> productIds = inputs[0].productIds;
        List<String> farpIdsFromInsert = new List<String>();
        List<Financial_Account_Related_Product__c> farps = new List<Financial_Account_Related_Product__c>();
        Integer i;
        for(i=0;i<wizFins.size();i++){
            Financial_Account_Related_Product__c farp = new Financial_Account_Related_Product__c();
            farp.Financial_Account__c = wizFins[i].Id;
            farp.Product__c = productIds[i];
            farp.Flow_Interview_Id__c = inputs[0].interviewId;
            farps.add(farp);
        }
        insert farps;
        List<Financial_Account_Related_Product__c> farpList = [SELECT Id FROM Financial_Account_Related_Product__c WHERE Flow_Interview_Id__c =: inputs[0].interviewId];
        System.debug('farps: ' + farps);
        System.debug('farpList: ' + farpList);
        List <FlowOutput> outputs = new List<FlowOutput>();
        FlowOutput objOutput = new FlowOutput();
        objOutput.count = farps.size();
        for(Financial_Account_Related_Product__c f : farps){
            farpIdsFromInsert.add(f.Id);
        }
        objOutput.farpIds = farpIdsFromInsert;
        outputs.add(objOutput);
        return outputs;
    }
    
    global class FlowInput {
        
        @InvocableVariable
        global List<Financial_Account__c> finAccts;
        
        @InvocableVariable
        global List<String> productIds;
             
        @InvocableVariable
        global String interviewId;
    }
    
    global class FlowOutput {
        
        @InvocableVariable
        global Integer count;
        
        @InvocableVariable
        global List<String> farpIds;
        
    }
}