unpackaged/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NOTIF-LOG-{000000}</displayFormat>
        <label>Notification Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Log__c/fields/Notification_Rule__c.field-meta.xml
<CustomField>
    <fullName>Notification_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Rule</label>
    <referenceTo>Notification_Rule__c</referenceTo>
    <relationshipLabel>Applied Notification Logs</relationshipLabel>
    <relationshipName>Applied_Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/Notification_Rule__c.object-meta.xml
<CustomObject>
    <label>Notification Rule</label>
    <nameField>
        <displayFormat>NR-{00000}</displayFormat>
        <label>Notification Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Rule__c/fields/Digest_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Digest_Cadence__c</fullName>
    <label>Digest Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/NotificationDeliveryEnqueueServiceTest.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-06-17
 */
@IsTest
private class NotificationDeliveryEnqueueServiceTest {
  @IsTest
  static void enqueueImmediateLogIdsDedupesAndSkipsDigest() {
    NotificationTestDataFactory.NotificationTestContext context = NotificationTestDataFactory.createHouseholdWithRecipient();
    Notification_Rule__c immediateRule = NotificationTestDataFactory.createUserPreference(
      NotificationConstants.OBJECT_TYPE_CASE,
      context.recipientUser.Id,
      NotificationConstants.CHANNEL_EMAIL,
      NotificationConstants.FREQUENCY_IMMEDIATE
    );
    Notification_Rule__c digestRule = NotificationTestDataFactory.createUserPreference(
      NotificationConstants.OBJECT_TYPE_CASE,
      context.recipientUser.Id,
      NotificationConstants.CHANNEL_IN_APP,
      NotificationConstants.FREQUENCY_DIGEST
    );

    Notification_Log__c immediateLog = NotificationTestDataFactory.createLogNotification(
      context.recipientUser.Id,
      context.household.Id,
      NotificationConstants.OBJECT_TYPE_CASE,
      NotificationConstants.STATUS_QUEUED,
      NotificationConstants.CHANNEL_EMAIL,
      NotificationConstants.FREQUENCY_IMMEDIATE,
      'Immediate enqueue test',
      null,
      immediateRule.Id
    );
    Notification_Log__c digestLog = NotificationTestDataFactory.createLogNotification(
      context.recipientUser.Id,
      context.household.Id,
      NotificationConstants.OBJECT_TYPE_CASE,
      NotificationConstants.STATUS_QUEUED,
      NotificationConstants.CHANNEL_IN_APP,
      NotificationConstants.FREQUENCY_DIGEST,
      'Digest enqueue test',
      null,
      digestRule.Id
    );

    List<Notification_Log__c> loadedLogs = new NotificationLogRepository().selectLogsByIds(
      new List<Id>{ immediateLog.Id, digestLog.Id }
    );
    System.assertEquals(
      1,
      NotificationDeliveryRequestBuilder.fromLogs(loadedLogs, true).size()
    );

    NotificationDeliveryDispatcher.testEnqueuedJobCount = 0;

    Test.startTest();
    NotificationDeliveryEnqueueService.enqueueImmediateLogIdStrings(
      new List<String>{
        String.valueOf(immediateLog.Id),
        String.valueOf(immediateLog.Id),
        String.valueOf(digestLog.Id)
      }
    );
    Test.stopTest();

    System.assertEquals(1, NotificationDeliveryDispatcher.testEnqueuedJobCount);
  }

  @IsTest
  static void enqueueLogIdsIncludesDigestRequests() {
    NotificationTestDataFactory.NotificationTestContext context = NotificationTestDataFactory.createHouseholdWithRecipient();
    Notification_Rule__c digestRule = NotificationTestDataFactory.createUserPreference(
      NotificationConstants.OBJECT_TYPE_CASE,
      context.recipientUser.Id,
      NotificationConstants.CHANNEL_EMAIL,
      NotificationConstants.FREQUENCY_DIGEST
    );
    digestRule.Digest_Cadence__c = NotificationConstants.DIGEST_FREQUENCY_DAILY;
    NotificationTestDataFactory.updateRecord(digestRule);

    Notification_Log__c digestLog = NotificationTestDataFactory.createLogNotification(
      context.recipientUser.Id,
      context.household.Id,
      NotificationConstants.OBJECT_TYPE_CASE,
      NotificationConstants.STATUS_QUEUED,
      NotificationConstants.CHANNEL_EMAIL,
      NotificationConstants.FREQUENCY_DIGEST,
      'Digest enqueue test',
      null,
      digestRule.Id
    );

    NotificationDeliveryDispatcher.testEnqueuedJobCount = 0;

    Test.startTest();
    NotificationDeliveryEnqueueService.enqueueLogIds(new List<Id>{ digestLog.Id });
    Test.stopTest();

    System.assertEquals(1, NotificationDeliveryDispatcher.testEnqueuedJobCount);
  }
}