unpackaged/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NOTIF-LOG-{000000}</displayFormat>
        <label>Notification Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Log__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>In_App</fullName>
                <label>In App</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <isActive>false</isActive>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Zoom</fullName>
                <isActive>false</isActive>
                <label>Zoom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>Digest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NotificationCenterDeliveryItem.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-06-17
 *
 * Flow-compatible delivery item for Notification Center Event handling.
 */
@JsonAccess(serializable='always' deserializable='always')
public class NotificationCenterDeliveryItem {
  @InvocableVariable(label='Log Id')
  public Id logId;

  @InvocableVariable(label='Log Ids CSV')
  public String logIdsCsv;

  @InvocableVariable(label='Recipient Id')
  public Id recipientId;

  @InvocableVariable(label='Channel')
  public String channel;

  @InvocableVariable(label='Frequency')
  public String frequency;

  @InvocableVariable(label='Source Type')
  public String sourceType;

  @InvocableVariable(label='Source Record Id')
  public String sourceRecordId;

  public static NotificationCenterDeliveryItem fromLog(
    Notification_Log__c logRecord
  ) {
    if (logRecord == null) {
      return null;
    }

    NotificationCenterDeliveryItem item = new NotificationCenterDeliveryItem();
    item.logId = logRecord.Id;
    item.recipientId = logRecord.Recipient__c;
    item.channel = logRecord.Channel__c;
    item.frequency = logRecord.Frequency__c;
    item.sourceType = logRecord.Source_Type__c;
    item.sourceRecordId = logRecord.Source_Record_Id__c;
    return item;
  }

  public static NotificationCenterDeliveryItem fromLogs(
    List<Notification_Log__c> logRecords
  ) {
    if (logRecords == null || logRecords.isEmpty()) {
      return null;
    }

    NotificationCenterDeliveryItem item = fromLog(logRecords[0]);
    List<String> logIds = new List<String>();

    for (Notification_Log__c logRecord : logRecords) {
      if (logRecord?.Id != null) {
        logIds.add(String.valueOf(logRecord.Id));
      }
    }

    item.logIdsCsv = String.join(logIds, ',');
    return item;
  }
}