unpackaged/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NOTIF-LOG-{000000}</displayFormat>
        <label>Notification Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Change_Context__c.field-meta.xml
<CustomField>
    <fullName>Change_Context__c</fullName>
    <label>Change Context</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>In_App</fullName>
                <label>In App</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <isActive>false</isActive>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Zoom</fullName>
                <isActive>false</isActive>
                <label>Zoom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Delivery_Attempt_Count__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Attempt_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Delivery Attempt Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>Digest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Notification_Rule__c.field-meta.xml
<CustomField>
    <fullName>Notification_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Rule</label>
    <referenceTo>Notification_Rule__c</referenceTo>
    <relationshipLabel>Applied Notification Logs</relationshipLabel>
    <relationshipName>Applied_Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Suppressed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Target_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Target_Record_Id__c</fullName>
    <label>Target Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/Notification_Rule__c.object-meta.xml
<CustomObject>
    <label>Notification Rule</label>
    <nameField>
        <displayFormat>NR-{00000}</displayFormat>
        <label>Notification Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Rule__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>In_App</fullName>
                <label>In App</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <isActive>false</isActive>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Zoom</fullName>
                <isActive>false</isActive>
                <label>Zoom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Digest_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Digest_Cadence__c</fullName>
    <label>Digest Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Digest_Frequency_Hour__c.field-meta.xml
<CustomField>
    <fullName>Digest_Frequency_Hour__c</fullName>
    <description>Hour of day (0-23) when hourly digest delivery should run.</description>
    <label>Digest Frequency Hour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8:00 AM</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10:00 AM</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11:00 AM</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12:00 PM</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>1:00 PM</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>2:00 PM</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>3:00 PM</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>4:00 PM</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>5:00 PM</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>6:00 PM</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>7:00 PM</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>8:00 PM</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>9:00 PM</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>10:00 PM</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>11:00 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
                <default>true</default>
                <label>Immediate</label>
            </value>
            <value>
                <fullName>Digest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Rules</relationshipLabel>
    <relationshipName>Notification_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Notification Rules</relationshipLabel>
    <relationshipName>Notification_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/NotificationDigestRepository.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-06-17
 *
 * SOQL access for scheduled digest batch scopes (rules and QueryLocators).
 */
public without sharing class NotificationDigestRepository {
  public Database.QueryLocator selectDigestRules(String cadence) {
    if (cadence == NotificationConstants.DIGEST_FREQUENCY_DAILY) {
      String currentHour = NotificationDigestTimezoneService.currentDigestHourValue();

      return Database.getQueryLocator(
        [
          SELECT
            Id,
            Object_Type__c,
            Channel__c,
            User__c,
            Household__c,
            Digest_Cadence__c,
            Digest_Frequency_Hour__c
          FROM Notification_Rule__c
          WHERE
            Is_Active__c = TRUE
            AND Frequency__c = :NotificationConstants.FREQUENCY_DIGEST
            AND Digest_Cadence__c = :cadence
            AND Digest_Frequency_Hour__c = :currentHour
        ]
      );
    }

    return Database.getQueryLocator(
      [
        SELECT
          Id,
          Object_Type__c,
          Channel__c,
          User__c,
          Household__c,
          Digest_Cadence__c,
          Digest_Frequency_Hour__c
        FROM Notification_Rule__c
        WHERE
          Is_Active__c = TRUE
          AND Frequency__c = :NotificationConstants.FREQUENCY_DIGEST
          AND Digest_Cadence__c = :cadence
      ]
    );
  }

  public Database.QueryLocator selectQueuedDigestLogsByIds(
    List<Id> logIds,
    String channel
  ) {
    if (String.isBlank(channel)) {
      return Database.getQueryLocator(
        [
          SELECT
            Id,
            Name,
            Recipient__c,
            Channel__c,
            Source_Type__c,
            Notification_Rule__c,
            Title__c,
            Body__c,
            Change_Context__c,
            CreatedDate,
            Source_Record_Id__c,
            Target_Record_Id__c,
            Household__c,
            Status__c,
            Frequency__c,
            Delivery_Attempt_Count__c
          FROM Notification_Log__c
          WHERE
            Id IN :logIds
            AND Status__c = :NotificationConstants.STATUS_QUEUED
            AND Frequency__c = :NotificationConstants.FREQUENCY_DIGEST
        ]
      );
    }

    return Database.getQueryLocator(
      [
        SELECT
          Id,
          Name,
          Recipient__c,
          Channel__c,
          Source_Type__c,
          Notification_Rule__c,
          Title__c,
          Body__c,
          Change_Context__c,
          CreatedDate,
          Source_Record_Id__c,
          Target_Record_Id__c,
          Household__c,
          Status__c,
          Frequency__c,
          Delivery_Attempt_Count__c
        FROM Notification_Log__c
        WHERE
          Id IN :logIds
          AND Status__c = :NotificationConstants.STATUS_QUEUED
          AND Frequency__c = :NotificationConstants.FREQUENCY_DIGEST
          AND Channel__c INCLUDES (:channel)
      ]
    );
  }

  public Database.QueryLocator selectQueuedDigestLogsForSourceRecords(
    List<Id> sourceRecordIds,
    Id recipientId,
    String objectType,
    String channel
  ) {
    Set<String> sourceRecordIdStrings = toSourceRecordIdStrings(sourceRecordIds);

    return Database.getQueryLocator(
      [
        SELECT
          Id,
          Name,
          Recipient__c,
          Channel__c,
          Source_Type__c,
          Notification_Rule__c,
          Title__c,
          Body__c,
          Change_Context__c,
          CreatedDate,
          Source_Record_Id__c,
          Target_Record_Id__c,
          Household__c,
          Status__c,
          Frequency__c,
          Delivery_Attempt_Count__c
        FROM Notification_Log__c
        WHERE
          Status__c = :NotificationConstants.STATUS_QUEUED
          AND Frequency__c = :NotificationConstants.FREQUENCY_DIGEST
          AND Source_Record_Id__c IN :sourceRecordIdStrings
          AND Recipient__c = :recipientId
          AND Source_Type__c = :objectType
          AND Channel__c INCLUDES (:channel)
      ]
    );
  }

  private static Set<String> toSourceRecordIdStrings(List<Id> sourceRecordIds) {
    Set<String> sourceRecordIdStrings = new Set<String>();

    if (sourceRecordIds == null) {
      return sourceRecordIdStrings;
    }

    for (Id sourceRecordId : sourceRecordIds) {
      if (sourceRecordId != null) {
        sourceRecordIdStrings.add(String.valueOf(sourceRecordId));
      }
    }

    return sourceRecordIdStrings;
  }
}