unpackaged/main/default/objects/ContentVersion/fields/Advertising_Type__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Type__c</fullName>
    <label>Advertising Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brochure/Worksheet/Pamphlet</fullName>
            </value>
            <value>
                <fullName>Business Card</fullName>
            </value>
            <value>
                <fullName>Business Envelope</fullName>
            </value>
            <value>
                <fullName>Email Signature</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Fax Coversheet</fullName>
            </value>
            <value>
                <fullName>Form Letter</fullName>
            </value>
            <value>
                <fullName>Group Email</fullName>
            </value>
            <value>
                <fullName>Letterhead</fullName>
            </value>
            <value>
                <fullName>Newsletter/Circular</fullName>
            </value>
            <value>
                <fullName>Periodical Print/Reprint</fullName>
            </value>
            <value>
                <fullName>Postcard</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Press Release</fullName>
            </value>
            <value>
                <fullName>Public Appearance</fullName>
            </value>
            <value>
                <fullName>Radio/TV Ad</fullName>
            </value>
            <value>
                <fullName>Seminar Handout</fullName>
            </value>
            <value>
                <fullName>Social Media Content</fullName>
            </value>
            <value>
                <fullName>Social Media Profile</fullName>
            </value>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>FINRA Review</fullName>
            </value>
            <value>
                <fullName>Video/Audio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ContentVersion/fields/Flow_Interview_ID__c.field-meta.xml
<CustomField>
    <fullName>Flow_Interview_ID__c</fullName>
    <label>Flow Interview ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/FileUploadController.cls
public class FileUploadController {
	
    @AuraEnabled 
    public static void updateCVs(List<String> cvIds, String adType, String interviewId){
        List<ContentVersion> cvListToUpdate = new List<ContentVersion>();
        if(adType == null && interviewId == null){
            return;
        }
        for(String cvId : cvIds){
            ContentVersion cv = new ContentVersion(Id = cvId);
            cv.Advertising_Type__c = adType;
            cv.Flow_Interview_ID__c = interviewId;
            cvListToUpdate.add(cv);
        }
        
        if(!cvListToUpdate.isEmpty()){
            update cvListToUpdate;
        }
    }
    
    @AuraEnabled 
    public static void updateCVsNonAdReview(List<String> cvIds, String interviewId){
        List<ContentVersion> cvListToUpdate = new List<ContentVersion>();
        
        for(String cvId : cvIds){
            ContentVersion cv = new ContentVersion(Id = cvId);
            cv.Flow_Interview_ID__c = interviewId;
            cvListToUpdate.add(cv);
        }
        
        if(!cvListToUpdate.isEmpty()){
            update cvListToUpdate;
        }
    }
    
	@AuraEnabled    
    public static List<String> getCVAdvertisingTypeOpts(){
       List<String> pickListValuesList= new List<String>();
		Schema.DescribeFieldResult fieldResult = ContentVersion.Advertising_Type__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
		for( Schema.PicklistEntry pickListVal : ple){
			pickListValuesList.add(pickListVal.getLabel());
            System.debug('picklist: ' + pickListVal.getLabel());
		}
        System.debug('picklist: ' + pickListValuesList);
		return pickListValuesList;
    }
}