unpackaged/main/default/objects/Account/fields/Classification__c.field-meta.xml
<CustomField>
    <fullName>Classification__c</fullName>
    <label>Classification</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COI</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Unclassified</fullName>
            </value>
            <value>
                <fullName>Regulatory Related Party</fullName>
                <isActive>false</isActive>
                <label>Regulatory Related Party</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Envelope__c/Envelope__c.object-meta.xml
<CustomObject>
    <label>Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Envelope__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Envelopes</relationshipLabel>
    <relationshipName>Envelopes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Envelope_Content__c/Envelope_Content__c.object-meta.xml
<CustomObject>
    <label>Envelope Content</label>
    <nameField>
        <displayFormat>WER-{000000}</displayFormat>
        <label>Envelope Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Envelope Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Envelope_Content__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Wizard_Envelope_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Envelope_Content__c/fields/Envelope__c.field-meta.xml
<CustomField>
    <fullName>Envelope__c</fullName>
    <label>Envelope</label>
    <referenceTo>Envelope__c</referenceTo>
    <relationshipLabel>Envelope Content</relationshipLabel>
    <relationshipName>Wizard_Envelope_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/EnvelopeHouseholdResolverTest.cls
@IsTest
private class EnvelopeHouseholdResolverTest {

    private static Account newHousehold(String name) {
        Account household = new Account(
            Name = name, Type = 'Other', Classification__c = 'Vendor;'
        );
        insert household;
        return household;
    }

    @IsTest
    static void returnsNullForBlankEnvelope() {
        System.assertEquals(null, EnvelopeHouseholdResolver.resolveHouseholdId((String) null));
        System.assertEquals(null, EnvelopeHouseholdResolver.resolveHouseholdId(''));
    }

    @IsTest
    static void returnsNullWhenEnvelopeHasNoResolvableHousehold() {
        Envelope__c env = new Envelope__c(Name = 'No Household');
        insert env;
        System.assertEquals(null, EnvelopeHouseholdResolver.resolveHouseholdId(env.Id));
    }

    @IsTest
    static void prefersEnvelopeHouseholdField() {
        Account household = newHousehold('Field Household');
        Envelope__c env = new Envelope__c(Name = 'Field Env', Household__c = household.Id);
        insert env;
        System.assertEquals(
            household.Id, EnvelopeHouseholdResolver.resolveHouseholdId(env.Id)
        );
    }

    @IsTest
    static void fallsBackToHouseholdJunctionRow() {
        Schema.RecordTypeInfo householdType = Account.SObjectType.getDescribe()
            .getRecordTypeInfosByDeveloperName()
            .get('Household');
        // The junction fallback keys on the Household Account record type; if the org has none, the
        // field-first path is the only one exercisable and the other tests already cover it.
        if (householdType == null || !householdType.isActive()) {
            return;
        }
        Account household = new Account(
            Name = 'Junction Household', RecordTypeId = householdType.getRecordTypeId()
        );
        insert household;
        Envelope__c env = new Envelope__c(Name = 'Junction Env');
        insert env;
        insert new Envelope_Content__c(Envelope__c = env.Id, Account__c = household.Id);

        System.assertEquals(
            household.Id, EnvelopeHouseholdResolver.resolveHouseholdId(env.Id)
        );
    }
}