unpackaged/main/default/objects/Account/fields/DMS_Addendum_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>DMS_Addendum_Signed_Date__c</fullName>
    <label>DMS Addendum Signed Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Envelope__c/Envelope__c.object-meta.xml
<CustomObject>
    <label>Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Envelope__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Envelopes</relationshipLabel>
    <relationshipName>Envelopes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Envelope_Content__c/Envelope_Content__c.object-meta.xml
<CustomObject>
    <label>Envelope Content</label>
    <nameField>
        <displayFormat>WER-{000000}</displayFormat>
        <label>Envelope Content Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Envelope Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Envelope_Content__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Wizard_Envelope_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Envelope_Content__c/fields/Envelope__c.field-meta.xml
<CustomField>
    <fullName>Envelope__c</fullName>
    <label>Envelope</label>
    <referenceTo>Envelope__c</referenceTo>
    <relationshipLabel>Envelope Content</relationshipLabel>
    <relationshipName>Wizard_Envelope_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Envelope_Content__c/fields/Required_Document__c.field-meta.xml
<CustomField>
    <fullName>Required_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Document</label>
    <referenceTo>Required_Documents__c</referenceTo>
    <relationshipLabel>Envelope Content</relationshipLabel>
    <relationshipName>Envelope_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/fields/BD_or_RIA__c.field-meta.xml
<CustomField>
    <fullName>BD_or_RIA__c</fullName>
    <label>BD or RIA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>RIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/fields/Brokerage__c.field-meta.xml
<CustomField>
    <fullName>Brokerage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brokerage</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Household that this financial account rolls up to.</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>HouseholdWizardFinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/fields/Managed_Account_Platform__c.field-meta.xml
<CustomField>
    <fullName>Managed_Account_Platform__c</fullName>
    <label>Managed Account Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AltMS</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>AMS (Wrap)</fullName>
            </value>
            <value>
                <fullName>AMS+</fullName>
            </value>
            <value>
                <fullName>BD Exclusion</fullName>
            </value>
            <value>
                <fullName>Courtesy Account</fullName>
            </value>
            <value>
                <fullName>DMS</fullName>
            </value>
            <value>
                <fullName>DMS (Wrap)</fullName>
            </value>
            <value>
                <fullName>EPS</fullName>
            </value>
            <value>
                <fullName>OMS</fullName>
            </value>
            <value>
                <fullName>TMS</fullName>
            </value>
            <value>
                <fullName>TMS (Wrap)</fullName>
            </value>
            <value>
                <fullName>AF2</fullName>
                <isActive>false</isActive>
                <label>AF2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Financial_Account_Role__c/Financial_Account_Role__c.object-meta.xml
<CustomObject>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{0000000}</displayFormat>
        <label>Financial Account Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Account_Role__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>Financial_Account_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account_Role__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Financial Account Roles</relationshipLabel>
    <relationshipName>Financial_Account_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Owner</fullName>
            </value>
            <value>
                <fullName>Joint Owner</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
            <value>
                <fullName>Custodian</fullName>
            </value>
            <value>
                <fullName>Trusted Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
    
    
    
    
    
</RecordType>

unpackaged/main/default/objects/PersonAccount/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
    
    
    
    
    
</RecordType>

unpackaged/main/default/objects/Required_Documents__c/Required_Documents__c.object-meta.xml
<CustomObject>
    <label>Required Document</label>
    <nameField>
        <label>Required Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Required_Documents__c/fields/DocuSign_Envelope__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Envelope__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DocuSign Envelope</label>
    <referenceTo>dfsle__Envelope__c</referenceTo>
    <relationshipLabel>Required Documents</relationshipLabel>
    <relationshipName>Required_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Required_Documents__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Required Documents</relationshipLabel>
    <relationshipName>Required_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Required_Documents__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Required Documents</relationshipLabel>
    <relationshipName>Required_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Signee__c/Signee__c.object-meta.xml
<CustomObject>
    <label>Signee</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Signee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Signee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Signee__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Signee</relationshipLabel>
    <relationshipName>Signee</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Signee__c/fields/Required_Document__c.field-meta.xml
<CustomField>
    <fullName>Required_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Required Document</label>
    <referenceTo>Required_Documents__c</referenceTo>
    <relationshipLabel>Signee</relationshipLabel>
    <relationshipName>Signee</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EnvelopeAccountAddendumServiceTest.cls
@isTest
private class EnvelopeAccountAddendumServiceTest {
  private static Id personRecordTypeId() {
    return Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('PersonAccount')
      .getRecordTypeId();
  }

  private static Account newOwner(String first, String last) {
    Account owner = new Account(
      FirstName = first,
      LastName = last,
      Type = 'Prospect',
      RecordTypeId = personRecordTypeId()
    );
    insert owner;
    return owner;
  }

  private static Id newHousehold() {
    Account household = new Account(
      Name = 'Test Household',
      RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Household')
        .getRecordTypeId()
    );
    insert household;
    return household.Id;
  }

  private static Financial_Account__c newAccount(String platform) {
    // A Household is required: the Financial_Account_Trigger stamps the household for DMS platforms
    // and updates it, which fails on a household-less account.
    Financial_Account__c fa = new Financial_Account__c(
      Name = 'Acct 1',
      BD_or_RIA__c = 'RIA',
      Managed_Account_Platform__c = platform,
      Household__c = newHousehold()
    );
    insert fa;
    return fa;
  }

  private static void addOwner(Id faId, Id ownerId, String role) {
    insert new Financial_Account_Role__c(
      Financial_Account__c = faId,
      Account__c = ownerId,
      Role__c = role
    );
  }

  private static Envelope__c newEnvelope() {
    Envelope__c env = new Envelope__c(Name = 'Test Envelope');
    insert env;
    return env;
  }

  private static List<Required_Documents__c> addenda(Id faId, String suffix) {
    return [
      SELECT Id, Name
      FROM Required_Documents__c
      WHERE Financial_Account__c = :faId AND Name LIKE :('%' + suffix)
    ];
  }

  // An RIA/DMS account with an unsigned owner earns a DMS Addendum named from the account, hung off
  // the account, linked to the envelope, and signed by that owner.
  @isTest
  static void testCreatesAddendumForUnsignedOwner() {
    Financial_Account__c fa = newAccount('DMS');
    Account owner = newOwner('Jane', 'Doe');
    addOwner(fa.Id, owner.Id, 'Primary Owner');
    Envelope__c env = newEnvelope();

    Test.startTest();
    EnvelopeAccountAddendumService.reconcile(fa.Id, env.Id);
    Test.stopTest();

    List<Required_Documents__c> docs = addenda(fa.Id, ' - DMS Addendum');
    System.assertEquals(1, docs.size(), 'A DMS Addendum should be created.');
    System.assertEquals('Acct 1 - DMS Addendum', docs[0].Name, 'Named from the account.');
    System.assertEquals(
      1,
      [
        SELECT COUNT()
        FROM Signee__c
        WHERE Required_Document__c = :docs[0].Id AND Account__c = :owner.Id
      ],
      'The unsigned owner signs the addendum.'
    );
    System.assertEquals(
      1,
      [
        SELECT COUNT()
        FROM Envelope_Content__c
        WHERE Envelope__c = :env.Id AND Required_Document__c = :docs[0].Id
      ],
      'The addendum is linked to the envelope.'
    );
  }

  // Only owners with a null signed-date sign: a joint owner who has already signed is not a signee.
  @isTest
  static void testOnlyUnsignedOwnersSign() {
    Financial_Account__c fa = newAccount('DMS');
    Account unsigned = newOwner('Jane', 'Doe');
    Account signed = newOwner('John', 'Roe');
    signed.DMS_Addendum_Signed_Date__c = Date.today();
    update signed;
    addOwner(fa.Id, unsigned.Id, 'Primary Owner');
    addOwner(fa.Id, signed.Id, 'Joint Owner');

    Test.startTest();
    EnvelopeAccountAddendumService.reconcile(fa.Id, null);
    Test.stopTest();

    Id docId = addenda(fa.Id, ' - DMS Addendum')[0].Id;
    System.assertEquals(
      1,
      [SELECT COUNT() FROM Signee__c WHERE Required_Document__c = :docId],
      'Exactly one signee — the unsigned owner.'
    );
    System.assertEquals(
      1,
      [
        SELECT COUNT()
        FROM Signee__c
        WHERE Required_Document__c = :docId AND Account__c = :unsigned.Id
      ],
      'The signee is the unsigned owner.'
    );
  }

  // When every owner has signed, no addendum is created.
  @isTest
  static void testNoAddendumWhenAllSigned() {
    Financial_Account__c fa = newAccount('AMS');
    Account owner = newOwner('Jane', 'Doe');
    owner.AMS_Addendum_Signed_Date__c = Date.today();
    update owner;
    addOwner(fa.Id, owner.Id, 'Primary Owner');

    Test.startTest();
    EnvelopeAccountAddendumService.reconcile(fa.Id, null);
    Test.stopTest();

    System.assertEquals(
      0,
      addenda(fa.Id, ' - AMS Addendum').size(),
      'No addendum when all owners have signed.'
    );
  }

  // A BD account gets no addendum even with a platform set.
  @isTest
  static void testBdAccountGetsNoAddendum() {
    // Brokerage + account number set to avoid an unrelated after-insert trigger path
    // (setReportAcctNumber_AfterInsert) that mutates read-only records for BD accounts without them.
    Financial_Account__c fa = new Financial_Account__c(
      Name = 'Acct 1',
      BD_or_RIA__c = 'BD',
      Managed_Account_Platform__c = 'DMS',
      Brokerage__c = true,
      Account_Number__c = '00012345',
      Household__c = newHousehold()
    );
    insert fa;
    Account owner = newOwner('Jane', 'Doe');
    addOwner(fa.Id, owner.Id, 'Primary Owner');

    Test.startTest();
    EnvelopeAccountAddendumService.reconcile(fa.Id, null);
    Test.stopTest();

    System.assertEquals(
      0,
      addenda(fa.Id, ' - DMS Addendum').size(),
      'A BD account earns no platform addendum.'
    );
  }

  // A platform change removes the stale addendum and creates the new one.
  @isTest
  static void testPlatformChangeSwapsAddendum() {
    Financial_Account__c fa = newAccount('DMS');
    Account owner = newOwner('Jane', 'Doe');
    addOwner(fa.Id, owner.Id, 'Primary Owner');
    EnvelopeAccountAddendumService.reconcile(fa.Id, null);
    System.assertEquals(1, addenda(fa.Id, ' - DMS Addendum').size(), 'DMS created first.');

    fa.Managed_Account_Platform__c = 'AMS';
    update fa;

    Test.startTest();
    EnvelopeAccountAddendumService.reconcile(fa.Id, null);
    Test.stopTest();

    System.assertEquals(
      0,
      addenda(fa.Id, ' - DMS Addendum').size(),
      'The stale DMS addendum is removed.'
    );
    System.assertEquals(
      1,
      addenda(fa.Id, ' - AMS Addendum').size(),
      'The AMS addendum is created.'
    );
  }

  // An addendum already handed to DocuSign is not removed when the platform changes.
  @isTest
  static void testSentAddendumIsPreserved() {
    Financial_Account__c fa = newAccount('DMS');
    Account owner = newOwner('Jane', 'Doe');
    addOwner(fa.Id, owner.Id, 'Primary Owner');
    EnvelopeAccountAddendumService.reconcile(fa.Id, null);

    // Simulate the addendum having been sent.
    dfsle__Envelope__c dse = new dfsle__Envelope__c();
    insert dse;
    Required_Documents__c doc = addenda(fa.Id, ' - DMS Addendum')[0];
    doc.DocuSign_Envelope__c = dse.Id;
    update doc;

    fa.Managed_Account_Platform__c = 'OMS';
    update fa;

    Test.startTest();
    EnvelopeAccountAddendumService.reconcile(fa.Id, null);
    Test.stopTest();

    System.assertEquals(
      1,
      addenda(fa.Id, ' - DMS Addendum').size(),
      'A sent addendum is left in place.'
    );
  }

  @isTest
  static void testNullAccountIsNoOp() {
    Test.startTest();
    EnvelopeAccountAddendumService.reconcile(null, null);
    Test.stopTest();
    System.assertEquals(
      0,
      [SELECT COUNT() FROM Required_Documents__c],
      'Null input creates nothing.'
    );
  }
}