unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Account_Account_Relationship__c/Account_Account_Relationship__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as a Household and a Business account.</description>
    <label>Account Account Relationship</label>
    <nameField>
        <displayFormat>AAR-{0000}</displayFormat>
        <label>Account Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relationshipa</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Account Relationshipa</relationshipLabel>
    <relationshipName>Account_Account_Relationshipa</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the relationship is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Reciprocal_Role__c.field-meta.xml
<CustomField>
    <fullName>Reciprocal_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Reciprocal_Role__c for member account relationships on the map.</description>
    <label>Role</label>
    <referenceTo>Reciprocal_Role__c</referenceTo>
    <relationshipLabel>Account Account Relationshipa</relationshipLabel>
    <relationshipName>Account_Account_Relationshipa</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Account Relationship (Related Account)</relationshipLabel>
    <relationshipName>Account_Account_Relationship1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Aunt / Uncle</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Client Entity</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Ex-Spouse</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Grandchild</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>In-Law</fullName>
            </value>
            <value>
                <fullName>Life Partner</fullName>
            </value>
            <value>
                <fullName>Nephew</fullName>
            </value>
            <value>
                <fullName>Niece / Nephew</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>529 Beneficiary</fullName>
            </value>
            <value>
                <fullName>Account Beneficiary</fullName>
            </value>
            <value>
                <fullName>Authorized Person</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Control Person</fullName>
            </value>
            <value>
                <fullName>Custodian (Minor)</fullName>
            </value>
            <value>
                <fullName>Executor / Personal Representative</fullName>
            </value>
            <value>
                <fullName>Guardian / Conservator</fullName>
            </value>
            <value>
                <fullName>Plan Administrator</fullName>
            </value>
            <value>
                <fullName>Plan Participant</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Trust Beneficiary</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Grantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Business</label>
</RecordType>

unpackaged/main/default/objects/Account_Account_Relationship__c/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household New Field</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Household New Field)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team__c/fields/Primary_Financial_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Financial_Advisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Financial Advisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Financial_Advisor_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
    
    
    
    
    
</RecordType>

unpackaged/main/default/objects/PersonAccount/recordTypes/Prospect.recordType-meta.xml
<RecordType>
    <fullName>Prospect</fullName>
    <active>true</active>
    <label>Prospect</label>
    
    
    
    
    
</RecordType>

unpackaged/main/default/objects/Reciprocal_Role__c/Reciprocal_Role__c.object-meta.xml
<CustomObject>
    <label>Reciprocal Role</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Reciprocal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reciprocal_Role__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Reciprocal Roles</relationshipLabel>
    <relationshipName>Reciprocal_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ArcRecordSummaryControllerTest.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-08-13
 */
@IsTest
private class ArcRecordSummaryControllerTest {

  @IsTest
  static void loadReturnsRecordSummaryContext() {
    Account member = new Account(
      FirstName = 'David',
      LastName = 'Harrison',
      Type = 'Active Client',
      RecordTypeId = Schema.SObjectType.Account
        .getRecordTypeInfosByDeveloperName()
        .get('PersonAccount')
        .getRecordTypeId()
    );
    insert member;

    Test.startTest();
    ArcRecordSummaryController.RecordSummaryContext context =
      ArcRecordSummaryController.load(member.Id);
    Test.stopTest();

    System.assertEquals('PersonAccount', context.recordTypeDeveloperName);
    System.assertEquals('Active Client', context.accountType);
    System.assertEquals('Active Client', context.status);
    System.assertNotEquals(null, context.createdDate);
  }

  @IsTest
  static void loadRequiresAccountId() {
    Boolean threw = false;

    try {
      ArcRecordSummaryController.load(null);
    } catch (AuraHandledException error) {
      threw = true;
    }

    System.assertEquals(true, threw, 'Expected required Account Id error.');
  }

  @IsTest
  static void loadRejectsARecordThatIsNotAnAccount() {
    Case aCase = new Case(Subject = 'Not an account', Status = 'New');
    insert aCase;

    Boolean threw = false;
    try {
      ArcRecordSummaryController.load(aCase.Id);
    } catch (AuraHandledException error) {
      threw = true;
    }

    Assert.isTrue(threw, 'A non-Account record Id must be rejected.');
  }

  @IsTest
  static void loadThrowsWhenAccountNotFound() {
    Account transient = new Account(Name = 'Transient Account', Type = 'Prospect');
    insert transient;
    Id deletedId = transient.Id;
    delete transient;

    Boolean threw = false;
    try {
      ArcRecordSummaryController.load(deletedId);
    } catch (AuraHandledException error) {
      threw = true;
    }

    Assert.isTrue(threw, 'A record that no longer exists must be reported as not found.');
  }

  @IsTest
  static void loadResolvesHouseholdAndAdvisorTeamContext() {
    Id householdRecordTypeId = Schema.SObjectType.Account
      .getRecordTypeInfosByDeveloperName()
      .get('Household')
      .getRecordTypeId();
    Id businessRecordTypeId = Schema.SObjectType.Account
      .getRecordTypeInfosByDeveloperName()
      .get('Business')
      .getRecordTypeId();

    Account household = new Account(
      Name = 'Harrison Household',
      Type = 'Prospect',
      RecordTypeId = householdRecordTypeId
    );
    insert household;

    // Financial_Advisor_Team_TriggerHandler.updateRepCode (fired indirectly by
    // inserting a team with a Primary Financial Advisor, through the team
    // member automation) does a strict `= [SELECT ... WHERE Name = 'Default
    // Team']` with no LIMIT-1 guard, which throws List-has-no-rows in a test
    // context with no such team. Seeding one first (with no advisor of its
    // own, so its own insert does not cascade) lets that query find a row.
    insert new Financial_Advisor_Team__c(Name = 'Default Team');

    Financial_Advisor_Team__c team = new Financial_Advisor_Team__c(
      Name = 'Team Alpha',
      Primary_Financial_Advisor__c = UserInfo.getUserId()
    );
    insert team;

    Account member = new Account(
      Name = 'Harrison Holdings',
      Type = 'Active Client',
      RecordTypeId = businessRecordTypeId,
      Household__c = household.Id,
      Financial_Advisor_Team__c = team.Id
    );
    insert member;

    Account otherParty = new Account(Name = 'Related Party', Type = 'Prospect');
    insert otherParty;

    Reciprocal_Role__c trusteeAndGrantor = new Reciprocal_Role__c(Role__c = 'Trustee;Grantor');
    Reciprocal_Role__c trusteeAgain = new Reciprocal_Role__c(Role__c = 'Trustee;Beneficiary');
    insert new List<Reciprocal_Role__c>{ trusteeAndGrantor, trusteeAgain };

    insert new List<Account_Account_Relationship__c>{
      new Account_Account_Relationship__c(
        Account__c = otherParty.Id,
        Related_Account__c = member.Id,
        Reciprocal_Role__c = trusteeAndGrantor.Id,
        Active__c = true
      ),
      new Account_Account_Relationship__c(
        Account__c = otherParty.Id,
        Related_Account__c = member.Id,
        Reciprocal_Role__c = trusteeAgain.Id,
        Active__c = true
      )
    };

    User runningUser = [
      SELECT FirstName, LastName, Name
      FROM User
      WHERE Id = :UserInfo.getUserId()
    ];
    List<String> nameParts = new List<String>();
    if (String.isNotBlank(runningUser.FirstName)) {
      nameParts.add(runningUser.FirstName.trim());
    }
    if (String.isNotBlank(runningUser.LastName)) {
      nameParts.add(runningUser.LastName.trim());
    }
    String expectedAdvisorName = nameParts.isEmpty()
      ? runningUser.Name
      : String.join(nameParts, ' ');

    Test.startTest();
    ArcRecordSummaryController.RecordSummaryContext context =
      ArcRecordSummaryController.load(member.Id);
    Test.stopTest();

    Assert.areEqual('Business', context.recordTypeDeveloperName);
    Assert.areEqual(household.Id, context.householdId);
    Assert.areEqual('Harrison Household', context.householdName);
    Assert.areEqual(expectedAdvisorName, context.primaryAdvisorName);
    Assert.areEqual('Active Client', context.accountType);

    Set<String> roleSet = new Set<String>(context.roles);
    Assert.isTrue(roleSet.contains('Trustee'), 'Trustee role should be present.');
    Assert.isTrue(roleSet.contains('Grantor'), 'Grantor role should be present.');
    Assert.isTrue(roleSet.contains('Beneficiary'), 'Beneficiary role should be present.');
    Assert.areEqual(
      3,
      context.roles.size(),
      'The duplicate Trustee role across both relationships should be de-duplicated.'
    );
  }
}