unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/AA_Account_Number_Wizard__c.field-meta.xml
<CustomField>
    <fullName>AA_Account_Number_Wizard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AA - Account Number - Wizard</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Cases (AA - Account Number - Wizard)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household New Field</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Household New Field)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Envelope__c/Envelope__c.object-meta.xml
<CustomObject>
    <label>Envelope</label>
    <nameField>
        <label>Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Envelopes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Envelope__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Envelopes</relationshipLabel>
    <relationshipName>Envelopes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Envelope__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Account__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Household that this financial account rolls up to.</description>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>HouseholdWizardFinancialAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EnvelopeLookupOptionControllerTest.cls
@IsTest
public class EnvelopeLookupOptionControllerTest {

    @IsTest
    static void testSubmitEnvelope() {

        // Create Envelope
        Envelope__c envelope = new Envelope__c(
            Status__c = 'In Progress'
        );
        insert envelope;

        // Create Household Account
        Account household = new Account(
            Name = 'Test Household',
            recordTypeId = getHouseholdRecordTypeId(),
            Type = 'Prospect'
        );
        insert household;

        Test.startTest();

        Map<String, List<FieldDetailController.PicklistOption>> result =
            EnvelopeLookupOptionController.getLookupOptions(household.Id, envelope.Id);

        Test.stopTest();

        System.assertNotEquals(
            null,
            result,
            'Result Should not null'
        );
    }

    @IsTest
    static void getLookupOptionsReturnsFinancialAccountsForHousehold() {
        Envelope__c envelope = new Envelope__c(Status__c = 'In Progress');
        insert envelope;

        Account household = new Account(
            Name = 'Lookup Options Household',
            recordTypeId = getHouseholdRecordTypeId(),
            Type = 'Prospect'
        );
        insert household;

        Financial_Account__c finAccount = new Financial_Account__c(
            Name = 'Lookup Financial Account',
            Household__c = household.Id
        );
        insert finAccount;

        Test.startTest();
        Map<String, List<FieldDetailController.PicklistOption>> result =
            EnvelopeLookupOptionController.getLookupOptions(household.Id, envelope.Id);
        Test.stopTest();

        String key = 'Case|AA_Account_Number_Wizard__c';
        System.assert(result.containsKey(key),
            'A household with an eligible Financial Account should populate this lookup source.');
        Boolean found = false;
        for (FieldDetailController.PicklistOption opt : result.get(key)) {
            if (opt.value == finAccount.Id) {
                found = true;
                System.assertEquals('Lookup Financial Account', opt.label);
            }
        }
        System.assertEquals(true, found, 'The household\'s Financial Account should be an option.');
    }

    @IsTest
    static void getLookupOptionsOmitsSourceWhenRequiredBindIsMissing() {
        Envelope__c envelope = new Envelope__c(Status__c = 'In Progress');
        insert envelope;

        Test.startTest();
        Map<String, List<FieldDetailController.PicklistOption>> result =
            EnvelopeLookupOptionController.getLookupOptions(null, envelope.Id);
        Test.stopTest();

        System.assertEquals(false, result.containsKey('Case|AA_Account_Number_Wizard__c'),
            'Without a household id the source has no bind to run with, so it is omitted entirely.');
    }

    @IsTest
    static void getLookupOptionsOmitsSourceWhenHouseholdHasNoEligibleRecords() {
        Account household = new Account(
            Name = 'Empty Lookup Options Household',
            recordTypeId = getHouseholdRecordTypeId(),
            Type = 'Prospect'
        );
        insert household;

        Test.startTest();
        Map<String, List<FieldDetailController.PicklistOption>> result =
            EnvelopeLookupOptionController.getLookupOptions(household.Id, null);
        Test.stopTest();

        System.assertEquals(false, result.containsKey('Case|AA_Account_Number_Wizard__c'),
            'A source that resolves to no records is omitted rather than returned empty.');
    }

    private static Id getHouseholdRecordTypeId() {

        return [
            SELECT Id
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND developername = 'Household'
            LIMIT 1
        ].Id;
    }
}