unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Case_Branch_Name_DisplayName__c.field-meta.xml
<CustomField>
    <fullName>Case_Branch_Name_DisplayName__c</fullName>
    <formula>SUBSTITUTE(Case_Branch_Name__c, &quot; | &lt;/br&gt;&quot;, &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Due_Date_of_Current_Task__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_of_Current_Task__c</fullName>
    <label>Due Date of Current Task</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household New Field</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Household New Field)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NOTIF-LOG-{000000}</displayFormat>
        <label>Notification Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Change_Context__c.field-meta.xml
<CustomField>
    <fullName>Change_Context__c</fullName>
    <label>Change Context</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>In_App</fullName>
                <label>In App</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <isActive>false</isActive>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Zoom</fullName>
                <isActive>false</isActive>
                <label>Zoom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/NotificationCaseEmailContentServiceTest.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-07-24
 */
@IsTest
private class NotificationCaseEmailContentServiceTest {
  @IsTest
  static void buildIncludesLinkedCaseContactHouseholdAndLatestComment() {
    Account household = new Account(Name = 'Case Email Household');
    NotificationTestDataFactory.insertRecord(household);

    Contact contactRecord = new Contact(
      LastName = 'CaseContact',
      AccountId = household.Id
    );
    NotificationTestDataFactory.insertRecord(contactRecord);

    Case caseRecord = new Case(
      Subject = 'Portfolio Service Request',
      AccountId = household.Id,
      ContactId = contactRecord.Id,
      Status = 'New',
      Origin = 'Phone',
      Due_Date_of_Current_Task__c = Date.today().addDays(7)
    );
    NotificationTestDataFactory.insertRecord(caseRecord);

    caseRecord = [
      SELECT Id, Subject, Case_Branch_Name_DisplayName__c
      FROM Case
      WHERE Id = :caseRecord.Id
      LIMIT 1
    ];

    contactRecord = [
      SELECT Id, Name, LastName
      FROM Contact
      WHERE Id = :contactRecord.Id
      LIMIT 1
    ];

    NotificationTestDataFactory.insertRecord(new CaseComment(
      ParentId = caseRecord.Id,
      CommentBody = 'Latest case comment for email body.',
      IsPublished = true
    ));
    NotificationChangeModels.ChangeContext changeContext = new NotificationChangeModels.ChangeContext(
      NotificationConstants.OBJECT_TYPE_CASE,
      NotificationConstants.CHANGE_TYPE_INSERT
    );

    Notification_Log__c logRecord = new Notification_Log__c(
      Source_Type__c = NotificationConstants.OBJECT_TYPE_CASE,
      Source_Record_Id__c = String.valueOf(caseRecord.Id),
      Household__c = household.Id,
      Change_Context__c = changeContext.toJson(),
      Channel__c = NotificationConstants.CHANNEL_EMAIL
    );

    NotificationCaseEmailContentService.ContentResult result = NotificationCaseEmailContentService.build(
      logRecord
    );

    System.assertEquals('New case', result.title);
    System.assert(result.htmlBody.contains('/lightning/r/Case/'));
    System.assert(result.htmlBody.contains('/lightning/r/Contact/'));
    System.assert(result.htmlBody.contains('/lightning/r/Account/'));
    System.assert(result.htmlBody.contains('Case Summary Name'));
    System.assert(result.htmlBody.contains('Change Made'));
    System.assert(result.htmlBody.contains('Assigned To'));
    System.assert(result.htmlBody.contains('Financial Advisor Team'));
    System.assert(result.htmlBody.contains('Due Date'));
    System.assert(result.htmlBody.contains('Case Comments'));
    System.assert(
      result.htmlBody.contains(
        String.isBlank(caseRecord.Case_Branch_Name_DisplayName__c)
          ? caseRecord.Subject
          : caseRecord.Case_Branch_Name_DisplayName__c
      )
    );
    System.assert(result.htmlBody.contains('Portfolio Service Request'));
    System.assert(result.htmlBody.contains('Latest case comment for email body.'));
    System.assert(result.htmlBody.contains(contactRecord.Name), 'Expected linked contact name');
    System.assert(result.htmlBody.contains(household.Name));
    System.assert(result.htmlBody.contains('Case created'));
    System.assertEquals(String.valueOf(caseRecord.Id), result.targetRecordId);
  }

  @IsTest
  static void buildIncludesChangeSummaryForOwnerUpdate() {
    Account household = new Account(Name = 'Case Owner Household');
    NotificationTestDataFactory.insertRecord(household);

    User currentUser = [
      SELECT Id, Name
      FROM User
      WHERE Id = :UserInfo.getUserId()
      LIMIT 1
    ];
    User assigneeUser = [
      SELECT Id, Name
      FROM User
      WHERE IsActive = TRUE AND Id != :currentUser.Id
      LIMIT 1
    ];

    Case caseRecord = new Case(
      Subject = 'Owner change case',
      AccountId = household.Id,
      Status = 'New',
      OwnerId = currentUser.Id
    );
    NotificationTestDataFactory.insertRecord(caseRecord);

    NotificationChangeModels.ChangeContext changeContext = new NotificationChangeModels.ChangeContext(
      NotificationConstants.OBJECT_TYPE_CASE,
      NotificationConstants.CHANGE_TYPE_UPDATE
    );
    changeContext.changedFields.add(
      new NotificationChangeModels.FieldChange(
        'OwnerId',
        'Owner',
        String.valueOf(currentUser.Id),
        String.valueOf(assigneeUser.Id),
        currentUser.Name,
        assigneeUser.Name
      )
    );

    Notification_Log__c logRecord = new Notification_Log__c(
      Source_Type__c = NotificationConstants.OBJECT_TYPE_CASE,
      Source_Record_Id__c = String.valueOf(caseRecord.Id),
      Household__c = household.Id,
      Change_Context__c = changeContext.toJson(),
      Channel__c = NotificationConstants.CHANNEL_EMAIL
    );

    NotificationCaseEmailContentService.ContentResult result = NotificationCaseEmailContentService.build(
      logRecord
    );

    System.assertEquals('Case assignment changed', result.title);
    System.assert(
      result.htmlBody.contains(
        '<strong>Owner</strong><br/>Old: ' +
          currentUser.Name +
          '<br/>New: ' +
          assigneeUser.Name
      )
    );
  }

  @IsTest
  static void enrichLogUsesHtmlForEmailChannel() {
    Account household = new Account(Name = 'Digest Case Household');
    NotificationTestDataFactory.insertRecord(household);

    Case caseRecord = new Case(
      Subject = 'Digest Case',
      AccountId = household.Id,
      Status = 'New'
    );
    NotificationTestDataFactory.insertRecord(caseRecord);

    caseRecord = [
      SELECT Id, Subject, Case_Branch_Name_DisplayName__c
      FROM Case
      WHERE Id = :caseRecord.Id
      LIMIT 1
    ];

    Notification_Log__c logRecord = new Notification_Log__c(
      Source_Type__c = NotificationConstants.OBJECT_TYPE_CASE,
      Source_Record_Id__c = String.valueOf(caseRecord.Id),
      Household__c = household.Id,
      Change_Context__c = new NotificationChangeModels.ChangeContext(
          NotificationConstants.OBJECT_TYPE_CASE,
          NotificationConstants.CHANGE_TYPE_INSERT
        )
        .toJson(),
      Channel__c = NotificationConstants.CHANNEL_EMAIL
    );

    NotificationDigestContentService.enrichLog(logRecord);

    System.assertEquals('New case', logRecord.Title__c);
    System.assert(logRecord.Body__c.contains('<table'));
    System.assert(
      logRecord.Body__c.contains(
        String.isBlank(caseRecord.Case_Branch_Name_DisplayName__c)
          ? caseRecord.Subject
          : caseRecord.Case_Branch_Name_DisplayName__c
      )
    );
  }
}