unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Significant_Event__c/Significant_Event__c.object-meta.xml
<CustomObject>
    <label>Significant Event</label>
    <nameField>
        <label>Significant Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Significant Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Significant_Event__c/fields/Approximate_Date__c.field-meta.xml
<CustomField>
    <fullName>Approximate_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if the exact date is unknown</inlineHelpText>
    <label>Approximate Date</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Significant_Event__c/fields/End_Date_Optional__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Optional__c</fullName>
    <label>End Date (Optional)</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Significant_Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adoption</fullName>
            </value>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>College</fullName>
            </value>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Dream Vacation</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Health Diagnosis</fullName>
            </value>
            <value>
                <fullName>Marriage</fullName>
            </value>
            <value>
                <fullName>New Baby</fullName>
            </value>
            <value>
                <fullName>New Business</fullName>
            </value>
            <value>
                <fullName>New Home</fullName>
            </value>
            <value>
                <fullName>New Job</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Service Mission</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Significant_Event__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Significant Events</relationshipLabel>
    <relationshipName>Significant_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Significant_Event__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business, Institution, Household, Trust</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Significant Events</relationshipLabel>
    <relationshipName>Significant_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Significant_Event__c/fields/Other_Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Other_Event_Type__c</fullName>
    <label>Other Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Significant_Event__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person Account, Prospect, Diversify Related Person</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Significant Events (Person)</relationshipLabel>
    <relationshipName>Significant_Events_Person</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Significant_Event_Contact__c/Significant_Event_Contact__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Accounts to Significant Event</description>
    <label>Significant Event Contact</label>
    <nameField>
        <displayFormat>SEC-{0000000}</displayFormat>
        <label>Significant Event Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Significant Event Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Significant_Event_Contact__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the Individual, Business, Trust, or Retirement Plan for this Event</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Household, Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Significant_Event_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Significant_Event_Contact__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Significant Event Contacts</relationshipLabel>
    <relationshipName>Significant_Event_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Significant_Event_Contact__c/fields/Significant_Event__c.field-meta.xml
<CustomField>
    <fullName>Significant_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Significant Event</label>
    <referenceTo>Significant_Event__c</referenceTo>
    <relationshipName>Significant_Event_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/SignificantEventActionRepository.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-08-28
 *
 * Repository for Significant Event create/edit reads and writes.
 */
public with sharing class SignificantEventActionRepository {
  public static final String HOUSEHOLD_RECORD_TYPE = FscRelAccountRepository.HOUSEHOLD_RECORD_TYPE;
  public static final String LEGACY_HOUSEHOLD_RECORD_TYPE = FscRelAccountRepository.LEGACY_HOUSEHOLD_RECORD_TYPE;
  public static final String EVENT_TYPE_OTHER = 'Other';

  public Account selectContextAccount(Id accountId) {
    if (accountId == null) {
      return null;
    }

    List<Account> accounts = [
      SELECT
        Id,
        Name,
        IsPersonAccount,
        PersonContactId,
        Household__c,
        Financial_Advisor_Team__c,
        RecordType.DeveloperName,
        RecordType.Name
      FROM Account
      WHERE Id = :accountId
      LIMIT 1
    ];

    return accounts.isEmpty() ? null : accounts[0];
  }

  public List<Account> searchNonHouseholdAccounts(String searchTerm, Integer limitSize) {
    if (String.isBlank(searchTerm)) {
      return new List<Account>();
    }

    String trimmedTerm = searchTerm.trim();
    if (trimmedTerm.length() < 2) {
      return new List<Account>();
    }

    Integer safeLimit = limitSize == null || limitSize < 1
      ? 8
      : Math.min(limitSize, 25);
    String escapedTerm = String.escapeSingleQuotes(trimmedTerm);
    String likeTerm = '%' + escapedTerm + '%';

    Set<String> householdRecordTypeDeveloperNames = FscRelAccountRepository.selectHouseholdRecordTypeDeveloperNames();

    return [
      SELECT Id, Name, RecordType.DeveloperName, RecordType.Name
      FROM Account
      WHERE
        Name LIKE :likeTerm
        AND RecordType.DeveloperName NOT IN :householdRecordTypeDeveloperNames
      ORDER BY Name
      LIMIT :safeLimit
    ];
  }

  public Significant_Event__c selectSignificantEventById(Id significantEventId) {
    if (significantEventId == null) {
      return null;
    }

    List<Significant_Event__c> events = [
      SELECT
        Id,
        Name,
        Event_Type__c,
        Other_Event_Type__c,
        Start_Date__c,
        End_Date_Optional__c,
        Approximate_Date__c,
        Description__c,
        Household__c,
        Financial_Advisor_Team__c
      FROM Significant_Event__c
      WHERE Id = :significantEventId
      LIMIT 1
    ];

    return events.isEmpty() ? null : events[0];
  }

  public List<Significant_Event_Contact__c> selectParticipantsByEventId(
    Id significantEventId
  ) {
    if (significantEventId == null) {
      return new List<Significant_Event_Contact__c>();
    }

    return [
      SELECT
        Id,
        Name,
        Account__c,
        Account__r.Name,
        Significant_Event__c,
        Significant_Event__r.Name,
        Significant_Event__r.Event_Type__c,
        Significant_Event__r.Other_Event_Type__c,
        Significant_Event__r.Start_Date__c,
        Significant_Event__r.End_Date_Optional__c,
        Significant_Event__r.Approximate_Date__c,
        Significant_Event__r.Description__c,
        Significant_Event__r.Household__c,
        Significant_Event__r.Household__r.Name,
        Significant_Event__r.Financial_Advisor_Team__c,
        Significant_Event__r.Financial_Advisor_Team__r.Name,
        Financial_Advisor_Team__c
      FROM Significant_Event_Contact__c
      WHERE Significant_Event__c = :significantEventId
      ORDER BY Account__r.Name
    ];
  }

  public Significant_Event__c insertSignificantEvent(Significant_Event__c eventRecord) {
    insert eventRecord;
    return eventRecord;
  }

  public Significant_Event__c updateSignificantEvent(Significant_Event__c eventRecord) {
    update eventRecord;
    return eventRecord;
  }

  public void insertParticipants(List<Significant_Event_Contact__c> participants) {
    if (participants == null || participants.isEmpty()) {
      return;
    }

    insert participants;
  }

  public void updateParticipants(List<Significant_Event_Contact__c> participants) {
    if (participants == null || participants.isEmpty()) {
      return;
    }

    update participants;
  }

  public void deleteParticipants(List<Significant_Event_Contact__c> participants) {
    if (participants == null || participants.isEmpty()) {
      return;
    }

    delete participants;
  }

  public void deleteSignificantEvent(Significant_Event__c eventRecord) {
    if (eventRecord == null || eventRecord.Id == null) {
      return;
    }

    delete eventRecord;
  }

  public List<Significant_Event_Contact__c> selectParticipantsByAccountIds(
    Set<Id> accountIds
  ) {
    if (accountIds == null || accountIds.isEmpty()) {
      return new List<Significant_Event_Contact__c>();
    }

    return [
      SELECT
        Id,
        Name,
        Account__c,
        Account__r.Name,
        Significant_Event__c,
        Significant_Event__r.Name,
        Significant_Event__r.Event_Type__c,
        Significant_Event__r.Other_Event_Type__c,
        Significant_Event__r.Start_Date__c,
        Significant_Event__r.End_Date_Optional__c,
        Significant_Event__r.Approximate_Date__c,
        Significant_Event__r.Description__c,
        Significant_Event__r.Household__c,
        Significant_Event__r.Household__r.Name,
        Significant_Event__r.Financial_Advisor_Team__c,
        Significant_Event__r.Financial_Advisor_Team__r.Name
      FROM Significant_Event_Contact__c
      WHERE Account__c IN :accountIds
      ORDER BY
        Significant_Event__r.Start_Date__c DESC NULLS LAST,
        Account__r.Name
    ];
  }

  public List<Significant_Event_Contact__c> selectParticipantsByDirectEventAccountId(
    Id accountId
  ) {
    if (accountId == null) {
      return new List<Significant_Event_Contact__c>();
    }

    return [
      SELECT
        Id,
        Name,
        Account__c,
        Account__r.Name,
        Significant_Event__c,
        Significant_Event__r.Name,
        Significant_Event__r.Event_Type__c,
        Significant_Event__r.Other_Event_Type__c,
        Significant_Event__r.Start_Date__c,
        Significant_Event__r.End_Date_Optional__c,
        Significant_Event__r.Approximate_Date__c,
        Significant_Event__r.Description__c,
        Significant_Event__r.Household__c,
        Significant_Event__r.Household__r.Name,
        Significant_Event__r.Financial_Advisor_Team__c,
        Significant_Event__r.Financial_Advisor_Team__r.Name,
        Significant_Event__r.Person__c
      FROM Significant_Event_Contact__c
      WHERE
        Significant_Event__r.Household__c = :accountId
        OR Significant_Event__r.Person__c = :accountId
      ORDER BY
        Significant_Event__r.Start_Date__c DESC NULLS LAST,
        Account__r.Name
    ];
  }

  public List<Significant_Event_Contact__c> selectParticipantsByDirectEventAccountIds(
    Set<Id> accountIds
  ) {
    if (accountIds == null || accountIds.isEmpty()) {
      return new List<Significant_Event_Contact__c>();
    }

    return [
      SELECT
        Id,
        Name,
        Account__c,
        Account__r.Name,
        Significant_Event__c,
        Significant_Event__r.Name,
        Significant_Event__r.Event_Type__c,
        Significant_Event__r.Other_Event_Type__c,
        Significant_Event__r.Start_Date__c,
        Significant_Event__r.End_Date_Optional__c,
        Significant_Event__r.Approximate_Date__c,
        Significant_Event__r.Description__c,
        Significant_Event__r.Household__c,
        Significant_Event__r.Household__r.Name,
        Significant_Event__r.Financial_Advisor_Team__c,
        Significant_Event__r.Financial_Advisor_Team__r.Name,
        Significant_Event__r.Person__c
      FROM Significant_Event_Contact__c
      WHERE
        Significant_Event__r.Household__c IN :accountIds
        OR Significant_Event__r.Person__c IN :accountIds
      ORDER BY
        Significant_Event__r.Start_Date__c DESC NULLS LAST,
        Account__r.Name
    ];
  }

  public List<Significant_Event_Contact__c> selectParticipantsByFinancialAdvisorTeamIds(
    Set<Id> teamIds
  ) {
    if (teamIds == null || teamIds.isEmpty()) {
      return new List<Significant_Event_Contact__c>();
    }

    return [
      SELECT
        Id,
        Name,
        Account__c,
        Account__r.Name,
        Significant_Event__c,
        Significant_Event__r.Name,
        Significant_Event__r.Event_Type__c,
        Significant_Event__r.Other_Event_Type__c,
        Significant_Event__r.Start_Date__c,
        Significant_Event__r.End_Date_Optional__c,
        Significant_Event__r.Approximate_Date__c,
        Significant_Event__r.Description__c,
        Significant_Event__r.Household__c,
        Significant_Event__r.Household__r.Name,
        Significant_Event__r.Financial_Advisor_Team__c,
        Significant_Event__r.Financial_Advisor_Team__r.Name
      FROM Significant_Event_Contact__c
      WHERE Significant_Event__r.Financial_Advisor_Team__c IN :teamIds
      ORDER BY
        Significant_Event__r.Start_Date__c DESC NULLS LAST,
        Account__r.Name
    ];
  }
}