unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Documents_Ready__c.field-meta.xml
<CustomField>
    <fullName>Documents_Ready__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Documents Ready</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household New Field</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Household New Field)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Required_Documents__c.field-meta.xml
<CustomField>
    <fullName>Required_Documents__c</fullName>
    <label>Required Documents</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/DocuSign_Document__c/DocuSign_Document__c.object-meta.xml
<CustomObject>
    <label>DocuSign Document</label>
    <nameField>
        <displayFormat>DD-{0000000}</displayFormat>
        <label>DocuSign Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DocuSign Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DocuSign_Document__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>DocuSign Documents</relationshipLabel>
    <relationshipName>DocuSign_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/DocuSign_Document__c/fields/Send_to_Primary_Owner__c.field-meta.xml
<CustomField>
    <fullName>Send_to_Primary_Owner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to Primary Owner?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/DocuSign_Document__c/fields/Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Template_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template Type</label>
    <referenceTo>dfsle__EnvelopeConfiguration__c</referenceTo>
    <relationshipLabel>DocuSign Documents</relationshipLabel>
    <relationshipName>DocuSign_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This field may only lookup to Household Accounts.</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Household)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Individual</label>
    
    
    
    
    
</RecordType>

unpackaged/main/default/objects/Required_Documents__c/Required_Documents__c.object-meta.xml
<CustomObject>
    <label>Required Document</label>
    <nameField>
        <label>Required Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Required_Documents__c/fields/DocuSign_Envelope__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Envelope__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DocuSign Envelope</label>
    <referenceTo>dfsle__Envelope__c</referenceTo>
    <relationshipLabel>Required Documents</relationshipLabel>
    <relationshipName>Required_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Required_Documents__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Required Documents</relationshipLabel>
    <relationshipName>Required_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Required_Documents__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Envelope Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Required_Documents_TriggerHandlerTest.cls
@isTest
public class Required_Documents_TriggerHandlerTest {
    @testSetup
    public static void testData(){
        //create user
        Id adminProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id;
        User testUser = new User(LastName = 'Test User', 
                                 ProfileId = adminProfileId, 
                                 Username = System.now().millisecond() + 'testuser@test.com', 
                                 Email = 'testinguser5309@testing.invalid', 
                                 Alias = 'testuser',
                                 LanguageLocaleKey='en_US',
                                 LocaleSidKey='en_US',
                                 TimeZoneSidKey='America/Chicago',
                                 EmailEncodingKey = 'UTF-8');
        insert testUser;
        String householdRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        String paRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        List<Account> accList = new List<Account>();
        accList.add(new Account(Name = 'Test Household Account', RecordTypeId = householdRecTypeId));
        accList.add(new Account(FirstName = 'Test', LastName = 'Person Account 1', PersonEmail = 'test@test1.com', RecordTypeId = paRecTypeId));
        insert accList;
        
        Account personAccount =  [SELECT PersonContactId FROM Account WHERE LastName = 'Person Account 1' LIMIT 1];
        List<AccountContactRelation> acrs = new List<AccountContactRelation>();
        acrs.add(new AccountContactRelation(ContactId = personAccount.PersonContactId, AccountId = accList[0].Id, IsActive = true, Roles = 'Client', FinServ__Primary__c = true));
		insert acrs;
        
        Case testCase = new Case(AccountId = accList[0].Id, Status = 'New', Required_Documents__c = 'Test Document');
        insert testCase;
        
        Opportunity opp;
        System.runAs(testuser){
            opp = new Opportunity(Name = 'Test Opportunity', AccountId = accList[0].Id, 
                                              StageName = 'Qualification', CloseDate = Date.today());
            insert opp;}
        
        List<dfsle__EnvelopeConfiguration__c> envelopConfig = new List<dfsle__EnvelopeConfiguration__c>();
        envelopConfig.add(new dfsle__EnvelopeConfiguration__c(
            Name = 'DocusignConfig',
            dfsle__DocuSignId__c = String.valueOf(dfsle.UUID.randomUUID())
        ));
        insert envelopConfig;
        
        List<DocuSign_Document__c> docs = new List<DocuSign_Document__c>();
        docs.add(new DocuSign_Document__c(
            Opportunity__c=opp.Id,
            Template_Type__c = envelopConfig[0].Id,
            Send_to_Primary_Owner__c = true
        ));
        insert docs;
        
        // Create test Required_Documents__c record
        Required_Documents__c testDoc = new Required_Documents__c(
            Name = 'Test Document',
            Status__c = 'Draft',
            Household__c = accList[0].Id
        );
        insert testDoc;
    }
    
    @isTest
    public static void testUpdateRelatedCases(){
        Required_Documents__c reqDoc = [SELECT Id, Status__c, Docusign_Envelope__c FROM Required_Documents__c 
                                        WHERE Name = 'Test Document' LIMIT 1];
        
        Account acc = [SELECT Id, Name FROM Account WHERE Name = 'Test Household Account' LIMIT 1];
        Opportunity opp = [SELECT Id, Name FROM Opportunity LIMIT 1];
        // Mock the DocuSign eSignature API
        dfsle.TestUtils.setMock(new dfsle.ESignatureAPIMock());
        Test.startTest();
        User testDSUser = dfsle.UserMock.createDocuSignAdministrator();
        // Run the test as a DocuSign Sender. This is required by dfsle.EnvelopeService.sendEnvelope
        System.runAs(testDSUser) {
            DocuSign_OppEnvelopes.sendOppEnvelopes(opp.Id);
        }   
        Test.stopTest();
        List<dfsle__Envelope__c> envs = [SELECT Id FROM dfsle__Envelope__c];
        System.debug(envs);

        reqDoc.DocuSign_Envelope__c = envs[0].Id;
    	reqDoc.Status__c = 'Signed';
    	update reqDoc;
        
    	List<Case> updatedCases = [SELECT Id, Documents_Ready__c FROM Case];
        Assert.areEqual(1, updatedCases.size());
        Assert.areEqual(true, updatedCases[0].Documents_Ready__c);
        
        delete reqDoc;
    }
}