unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NOTIF-LOG-{000000}</displayFormat>
        <label>Notification Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>In_App</fullName>
                <label>In App</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <isActive>false</isActive>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Zoom</fullName>
                <isActive>false</isActive>
                <label>Zoom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Delivered_At__c.field-meta.xml
<CustomField>
    <fullName>Delivered_At__c</fullName>
    <label>Delivered At</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>Digest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Is_Read__c.field-meta.xml
<CustomField>
    <fullName>Is_Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Read</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Notification_Rule__c.field-meta.xml
<CustomField>
    <fullName>Notification_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Rule</label>
    <referenceTo>Notification_Rule__c</referenceTo>
    <relationshipLabel>Applied Notification Logs</relationshipLabel>
    <relationshipName>Applied_Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Suppressed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Suppression_Reason__c.field-meta.xml
<CustomField>
    <fullName>Suppression_Reason__c</fullName>
    <label>Suppression Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/Notification_Rule__c.object-meta.xml
<CustomObject>
    <label>Notification Rule</label>
    <nameField>
        <displayFormat>NR-{00000}</displayFormat>
        <label>Notification Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Rule__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>In_App</fullName>
                <label>In App</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <isActive>false</isActive>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Zoom</fullName>
                <isActive>false</isActive>
                <label>Zoom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
                <default>true</default>
                <label>Immediate</label>
            </value>
            <value>
                <fullName>Digest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Rules</relationshipLabel>
    <relationshipName>Notification_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Is_System_Default__c.field-meta.xml
<CustomField>
    <fullName>Is_System_Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marks org-wide template rules managed by Notification Center admins.</description>
    <inlineHelpText>When checked, this rule is a system default applied to all users until they override it.</inlineHelpText>
    <label>System Default</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <label>Object Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Priority</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Notification Rules</relationshipLabel>
    <relationshipName>Notification_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/NotificationTestDataFactory.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-06-03
 *
 * Shared test data for notification framework tests.
 */
@IsTest
public class NotificationTestDataFactory {
  public class NotificationTestContext {
    public Account household;
    public User recipientUser;
  }

  public static NotificationTestContext createHouseholdWithRecipient() {
    NotificationTestContext context = new NotificationTestContext();

    System.runAs(runningUser()) {
      context.household = FscDataTestDataFactory.createHouseholdAccount(
        'Notification Test Household'
      );
    }

    context.recipientUser = [
      SELECT Id, Profile.Name
      FROM User
      WHERE Id = :UserInfo.getUserId()
      LIMIT 1
    ];

    NotificationRecipientService.testRecipientOverrides = new Map<Id, List<Id>>{
      context.household.Id => new List<Id>{ context.recipientUser.Id }
    };

    return context;
  }

  public static NotificationTestContext createHouseholdWithStandardUserRecipient() {
    NotificationTestContext context = new NotificationTestContext();

    context.recipientUser = createStandardUser('notifrcpt');

    System.runAs(runningUser()) {
      context.household = FscDataTestDataFactory.createHouseholdAccount(
        'Notification Test Household'
      );
    }

    NotificationRecipientService.testRecipientOverrides = new Map<Id, List<Id>>{
      context.household.Id => new List<Id>{ context.recipientUser.Id }
    };

    return context;
  }

  public static void insertRecord(SObject record) {
    if (record == null) {
      return;
    }

    insertRecords(new List<SObject>{ record });
  }

  public static void insertRecords(List<SObject> records) {
    if (records == null || records.isEmpty()) {
      return;
    }

    System.runAs(runningUser()) {
      insert records;
    }
  }

  public static void updateRecord(SObject record) {
    if (record == null) {
      return;
    }

    updateRecords(new List<SObject>{ record });
  }

  public static void updateRecords(List<SObject> records) {
    if (records == null || records.isEmpty()) {
      return;
    }

    System.runAs(runningUser()) {
      update records;
    }
  }

  public static void clearTestOverrides() {
    NotificationRecipientService.testRecipientOverrides = null;
  }

  public static String defaultChannel() {
    return NotificationChannelService.getDefaultChannelApiName();
  }

  public static String channel(String apiName) {
    System.assert(
      NotificationChannelService.getActiveChannelApiNames().contains(apiName),
      'Expected active channel: ' + apiName
    );
    return apiName;
  }

  public static String alternateChannel() {
    String defaultChannel = defaultChannel();
    for (String channelApiName : NotificationChannelService.getActiveChannelApiNames()) {
      if (channelApiName != defaultChannel) {
        return channelApiName;
      }
    }

    return defaultChannel();
  }

  public static Notification_Rule__c createGlobalPreference(String objectType) {
    return createPreference(
      objectType,
      null,
      null,
      NotificationChannelService.getDefaultChannelApiName(),
      NotificationConstants.FREQUENCY_IMMEDIATE,
      0
    );
  }

  public static Notification_Rule__c createUserPreference(
    String objectType,
    Id userId,
    String channel,
    String frequency
  ) {
    return createPreference(objectType, userId, null, channel, frequency, 10);
  }

  public static Notification_Rule__c createUserPreference(
    String objectType,
    Id userId,
    List<String> channels,
    String frequency
  ) {
    return createPreference(
      objectType,
      userId,
      null,
      joinChannels(channels),
      frequency,
      10
    );
  }

  public static Notification_Rule__c createHouseholdPreference(
    String objectType,
    Id householdId,
    String channel,
    String frequency
  ) {
    return createPreference(objectType, null, householdId, channel, frequency, 10);
  }

  public static Notification_Rule__c createUserHouseholdPreference(
    String objectType,
    Id userId,
    Id householdId,
    List<String> channels,
    String frequency
  ) {
    return createPreference(
      objectType,
      userId,
      householdId,
      joinChannels(channels),
      frequency,
      20
    );
  }

  public static String joinChannels(List<String> channels) {
    if (channels == null || channels.isEmpty()) {
      return null;
    }

    List<String> normalizedChannels = new List<String>();
    for (String channel : channels) {
      if (!String.isBlank(channel)) {
        normalizedChannels.add(channel.trim());
      }
    }

    return normalizedChannels.isEmpty()
      ? null
      : String.join(normalizedChannels, ';');
  }

  public static Notification_Rule__c createUserHouseholdPreference(
    String objectType,
    Id userId,
    Id householdId,
    String channel,
    String frequency
  ) {
    return createPreference(objectType, userId, householdId, channel, frequency, 20);
  }

  @TestVisible
  public static Notification_Rule__c createPreference(
    String objectType,
    Id userId,
    Id householdId,
    String channel,
    String frequency,
    Decimal priority
  ) {
    Notification_Rule__c preference = new Notification_Rule__c(
      Object_Type__c = objectType,
      Channel__c = channel,
      Frequency__c = frequency,
      Is_Active__c = true,
      Is_System_Default__c = userId == null && householdId == null,
      Priority__c = priority,
      User__c = userId,
      Household__c = householdId
    );
    insertRecord(preference);
    return preference;
  }

  public static Notification_Log__c createSentInAppNotification(
    Id recipientId,
    Id householdId,
    String sourceType,
    String title,
    String body,
    Boolean isRead
  ) {
    Notification_Log__c notification = new Notification_Log__c(
      Recipient__c = recipientId,
      Household__c = householdId,
      Source_Type__c = sourceType,
      Channel__c = NotificationConstants.CHANNEL_IN_APP,
      Status__c = NotificationConstants.STATUS_SENT,
      Title__c = title,
      Body__c = body,
      Is_Read__c = isRead,
      Delivered_At__c = System.now()
    );
    insertRecord(notification);
    return notification;
  }

  public static Notification_Log__c createLogNotification(
    Id recipientId,
    Id householdId,
    String sourceType,
    String status,
    String channel,
    String frequency,
    String title,
    String suppressionReason,
    Id preferenceId
  ) {
    Notification_Log__c notification = new Notification_Log__c(
      Recipient__c = recipientId,
      Household__c = householdId,
      Source_Type__c = sourceType,
      Channel__c = channel,
      Status__c = status,
      Frequency__c = frequency,
      Title__c = title,
      Body__c = title,
      Suppression_Reason__c = suppressionReason,
      Notification_Rule__c = preferenceId,
      Delivered_At__c = status == NotificationConstants.STATUS_SENT
        ? System.now()
        : null
    );
    insertRecord(notification);
    return notification;
  }

  @TestVisible
  public static User createStandardUser(String aliasPrefix) {
    Profile standardProfile = [
      SELECT Id
      FROM Profile
      WHERE Name = 'Standard User'
      LIMIT 1
    ];

    String uniqueSuffix = String.valueOf(System.currentTimeMillis());
    User testUser = new User(
      Alias = aliasPrefix.left(8),
      Email = aliasPrefix + '@example.com.test',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Notification Test User',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = standardProfile.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      Username = aliasPrefix + uniqueSuffix + '@example.com.test'
    );
    insert testUser;
    stripAutomationPermissionSetAssignments(testUser.Id);
    return testUser;
  }

  @TestVisible
  public static User createProfileUser(String profileName, String aliasPrefix) {
    Profile profileRecord = [
      SELECT Id
      FROM Profile
      WHERE Name = :profileName
      LIMIT 1
    ];

    String uniqueSuffix = String.valueOf(System.currentTimeMillis());
    User testUser = new User(
      Alias = aliasPrefix.left(8),
      Email = aliasPrefix + '@example.com.test',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Notification Profile Test User',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = profileRecord.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      Username = aliasPrefix + uniqueSuffix + '@example.com.test'
    );
    insert testUser;
    stripAutomationPermissionSetAssignments(testUser.Id);
    return testUser;
  }

  @TestVisible
  public static User runningUser() {
    return new User(Id = UserInfo.getUserId());
  }

  private static void stripAutomationPermissionSetAssignments(Id userId) {
    delete [
      SELECT Id
      FROM PermissionSetAssignment
      WHERE
        AssigneeId = :userId
        AND (PermissionSetGroupId != NULL OR PermissionSet.IsOwnedByProfile = FALSE)
    ];
  }
}