unpackaged/main/default/objects/Account/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Household must be an account with the Household record type.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Household</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Household)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Notes__c/Notes__c.object-meta.xml
<CustomObject>
    <label>Notes</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notes__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notes__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notes (Household)</relationshipLabel>
    <relationshipName>Notes1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notes__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notes__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>CRS Delivered</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notes_Template__c/Notes_Template__c.object-meta.xml
<CustomObject>
    <label>Notes Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notes_Template__c/fields/Is_Public__c.field-meta.xml
<CustomField>
    <fullName>Is_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Public</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Notes_Template__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/PrivateNotesComponentControllerTest.cls
@isTest
private class PrivateNotesComponentControllerTest{
    
    private static testMethod void testPrivateNotesComponentController() {
        String recTypeId = [SELECT Id FROM RecordType WHERE (Name = 'Person Account') AND (SobjectType = 'Account')].Id;
        String recTypeIdHouseHold = [SELECT Id FROM RecordType WHERE (Name = 'Household') AND (SobjectType = 'Account')].Id;
        
        Account newAccount = new Account(RecordTypeID = recTypeId, FirstName = 'Test FName', LastName = 'Test LName', PersonEmail = 'test@test.com');        
        Account newHouseHoldAccount = new Account(RecordTypeID = recTypeIdHouseHold, Name = 'Test');        
        insert new List<Account>{newAccount, newHouseHoldAccount};         
            
            Notes__c notes = new Notes__c(Name = 'Test', Note__c = 'Test', Type__c = 'Call', Client__c = newAccount.Id);
        Notes__c noteHouseHold = new Notes__c(Name = 'Test', Note__c = 'Test', Type__c = 'Call', Household__c = newHouseHoldAccount.Id);
        List<Notes__c> lstNotes = new List<Notes__c>{notes, noteHouseHold};  
        insert lstNotes;
            
            PrivateNotesComponentController.NoteWrapper wrap = PrivateNotesComponentController.fetchNotesRecords(newAccount.Id, 'Account');
        System.assertEquals('Client__c', wrap.fieldName, 'Notes Wrappper field Name should be Client');
        System.assertEquals(1, wrap.notesList.size(), 'Notes size should be 1');
        
        wrap = PrivateNotesComponentController.fetchNotesRecords(newHouseHoldAccount.Id, 'Account');
        System.assertEquals('Household__c', wrap.fieldName, 'Notes Wrappper field Name should be Household');
        System.assertEquals(1, wrap.notesList.size(), 'Notes size should be 1');
        
        Test.startTest();
        PrivateNotesComponentController.NoteWrapper notesList = PrivateNotesComponentController.searchNotesRecords(newAccount.Id, 'Test', 'Call', Null, Null,lstNotes);
        //System.assertEquals(1, notesList.size(), 'Notes size should be 1');
        
        notesList = PrivateNotesComponentController.searchNotesRecords(newAccount.Id, 'Test', 'Call, Meeting', Null, Date.today(),lstNotes);
        //System.assertEquals(0, notesList.size(), 'Notes size should be zero');
        Test.stopTest();
        
        notesList = PrivateNotesComponentController.searchNotesRecords(newAccount.Id, 'Test', 'Call, Meeting', Date.today(), Null,lstNotes);
    }
    
    private static testMethod void testGetNotesTemplatesNotNull(){
        Notes_Template__c noteTemplate = new Notes_Template__c(
            Name='Call Note', 
            Note__c='This is a test template note');
        insert noteTemplate;
        
        Test.startTest();
        Map<String, String> noteTemplate1 = PrivateNotesComponentController.getNotesTemplates();
        Test.stopTest();
        Set<String> templateName = noteTemplate1.keySet();
        System.assertEquals('Call Note', templateName.iterator().next());
    }
    
    private static testMethod void testGetNotesTemplatesPublic(){
        Notes_Template__c noteTemplate = new Notes_Template__c(
            Name='Call Note', 
            Note__c='This is a test template note',
            Is_Public__c=true);
        insert noteTemplate;
        
        Test.startTest();
        Map<String, String> noteTemplate1 = PrivateNotesComponentController.getNotesTemplates();
        Test.stopTest();
        Set<String> templateName = noteTemplate1.keySet();
        System.assertEquals('Call Note', templateName.iterator().next());
    }
    private static testMethod void testGetNotesTemplatesNull(){
        Test.startTest();
        Map<String, String> noteTemplate1 = PrivateNotesComponentController.getNotesTemplates();
        Test.stopTest();
        System.assertEquals(null, noteTemplate1);
    }
}