unpackaged/main/default/objects/Account/fields/Incomplete_Record__c.field-meta.xml
<CustomField>
    <fullName>Incomplete_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incomplete Record</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Account_Closure_Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Account_Closure_Additional_Information__c</fullName>
    <label>Account Closure Additional Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Account_Closure_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Closure_End_Date__c</fullName>
    <label>Account Closure End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Account_Closure_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Account_Closure_Explanation__c</fullName>
    <label>Account Closure Explanation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Account_Closure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Account_Closure_Reason__c</fullName>
    <label>Account Closure Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Re-Registration</fullName>
            </value>
            <value>
                <fullName>Client Terminated Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Bond_Ladder__c.field-meta.xml
<CustomField>
    <fullName>Bond_Ladder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bond Ladder</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Date_of_Death__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Death__c</fullName>
    <label>Date of Death</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Flow_Interview_ID__c.field-meta.xml
<CustomField>
    <fullName>Flow_Interview_ID__c</fullName>
    <label>Flow Interview ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Incomplete_Record__c.field-meta.xml
<CustomField>
    <fullName>Incomplete_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incomplete Record</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Management_Style__c.field-meta.xml
<CustomField>
    <fullName>Management_Style__c</fullName>
    <label>Management Style</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DMS</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>OMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Needs_Principal_Review__c.field-meta.xml
<CustomField>
    <fullName>Needs_Principal_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Needs Principal Review</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Order_Tickets__c.field-meta.xml
<CustomField>
    <fullName>Order_Tickets__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Tickets</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Previous_Management_Style__c.field-meta.xml
<CustomField>
    <fullName>Previous_Management_Style__c</fullName>
    <label>Previous Management Style</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/STCM__c.field-meta.xml
<CustomField>
    <fullName>STCM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>STCM</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Wizard_Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Account__c/fields/Account_Closure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Account_Closure_Reason__c</fullName>
    <label>Account Closure Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Death</fullName>
            </value>
            <value>
                <fullName>Re-Registration</fullName>
            </value>
            <value>
                <fullName>Client Terminated Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipName>Wizard_Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/fields/Managed_Account_Platform__c.field-meta.xml
<CustomField>
    <fullName>Managed_Account_Platform__c</fullName>
    <label>Managed Account Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AltMS</fullName>
            </value>
            <value>
                <fullName>AMS</fullName>
            </value>
            <value>
                <fullName>AMS (Wrap)</fullName>
            </value>
            <value>
                <fullName>AMS+</fullName>
            </value>
            <value>
                <fullName>BD Exclusion</fullName>
            </value>
            <value>
                <fullName>Courtesy Account</fullName>
            </value>
            <value>
                <fullName>DMS</fullName>
            </value>
            <value>
                <fullName>DMS (Wrap)</fullName>
            </value>
            <value>
                <fullName>EPS</fullName>
            </value>
            <value>
                <fullName>OMS</fullName>
            </value>
            <value>
                <fullName>TMS</fullName>
            </value>
            <value>
                <fullName>TMS (Wrap)</fullName>
            </value>
            <value>
                <fullName>AF2</fullName>
                <isActive>false</isActive>
                <label>AF2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Ticket__c/Order_Ticket__c.object-meta.xml
<CustomObject>
    <label>Order Ticket</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Order Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Ticket__c/fields/Additional_Details__c.field-meta.xml
<CustomField>
    <fullName>Additional_Details__c</fullName>
    <label>Additional Details</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Bond_Ladder__c.field-meta.xml
<CustomField>
    <fullName>Bond_Ladder__c</fullName>
    <formula>Strategy__r.Bond_Ladder__c</formula>
    <label>Bond Ladder?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Date_of_First_Withdrawal__c.field-meta.xml
<CustomField>
    <fullName>Date_of_First_Withdrawal__c</fullName>
    <label>Date of First Withdrawal</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Flow_Interview_ID__c.field-meta.xml
<CustomField>
    <fullName>Flow_Interview_ID__c</fullName>
    <label>Flow Interview ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Incomplete_Record__c.field-meta.xml
<CustomField>
    <fullName>Incomplete_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Incomplete Record</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Method_of_Cash_Raise__c.field-meta.xml
<CustomField>
    <fullName>Method_of_Cash_Raise__c</fullName>
    <label>Method of Cash Raise</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pro-rata</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Method_to_Allocate__c.field-meta.xml
<CustomField>
    <fullName>Method_to_Allocate__c</fullName>
    <label>Method to Allocate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Allocate Pro-rata to Standard Trade Instructions</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Type_of_Request__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Request__c</fullName>
    <label>Type of Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New DMS Instructions</fullName>
            </value>
            <value>
                <fullName>Update DMS Instructions</fullName>
            </value>
            <value>
                <fullName>Raise Cash</fullName>
            </value>
            <value>
                <fullName>Instructions for Future Deposit</fullName>
            </value>
            <value>
                <fullName>Add Systematic Withdrawal</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Remove Systematic Withdrawal</fullName>
            </value>
            <value>
                <fullName>Add/Remove Systematic Withdrawals</fullName>
                <isActive>false</isActive>
                <label>Add/Remove Systematic Withdrawals</label>
            </value>
            <value>
                <fullName>Instructions for Future Deposits</fullName>
                <isActive>false</isActive>
                <label>Instructions for Future Deposits</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Wizard_Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FinancialAccountServiceWizard.cls
public with sharing class FinancialAccountServiceWizard {
    public class ServiceRequest {
        public String serviceType; // e.g., 'Additional Funding', 'TPMM', 'Account Closure', 'Manage DMS', 'Change Management'
        public String subServiceType; // e.g., 'Raise Cash', 'Future Deposits' (for DMS)
        
        public Id financialAccountId;
        public Id householdId;
        public Id primaryOwnerId;
        public Id personContactId;
        public String financialAccountName;
        public String currentManagedPlatform;
        public String advisorTeam;
        public Id recordTypeId;
        public String flowInterviewGuid;
        
        // TPMM & TMS Inputs
        public List<Id> uploadedDocumentIds = new List<Id>();
        
        // Account Closure Inputs
        public String closureReason;
        public Date closureEndDate;
        public Date dateOfDeath;
        public String closureExplanation;
        public String closureAdditionalInfo;
        
        // Order Ticket / DMS Inputs
        public Decimal requestAmount;
        public String methodToAllocate;
        public String additionalDetails;
        public String addOrRemove;
        public Date firstWithdrawalDate;
        public Date expectedEndDate;
        public String frequency;
        
        // Change Management Inputs
        public String newManagementStyle;
        
        // Bond Ladder / STCM Flags
        public Boolean isBondLadder = false;
        public Boolean isSTCM = false;
    }
    public static void processServiceRequests(List<ServiceRequest> requests) {
        List<Case> casesToInsert = new List<Case>();
        Map<Integer, ServiceRequest> requestMap = new Map<Integer, ServiceRequest>();
        
        // 1. Prepare Cases
        for (Integer i = 0; i < requests.size(); i++) {
            ServiceRequest req = requests[i];
            Case newCase = buildBaseCase(req);
            
            switch on req.serviceType {
                when 'Additional Funding' {
                    newCase = applyAdditionalFundingRules(newCase, req);
                }
                when 'Third Party Money Movement' {
                    newCase = applyTPMMRules(newCase, req);
                }
                when 'Account Closure' {
                    newCase = applyAccountClosureRules(newCase, req);
                }
                when 'Manage DMS Instructions' {
                    newCase = applyDMSInstructionRules(newCase, req);
                }
                when 'Change Management Style' {
                    newCase = applyChangeManagementRules(newCase, req);
                }
            }
            
            casesToInsert.add(newCase);
            requestMap.put(i, req);
        }
        
        if (!casesToInsert.isEmpty()) {
            insert casesToInsert;
        }
        
        // 2. Process Related Records (Order Tickets, CDLs, Account Updates)
        List<ContentDocumentLink> cdlsToInsert = new List<ContentDocumentLink>();
        List<Order_Ticket__c> ticketsToInsert = new List<Order_Ticket__c>();
        Map<Id, Account> accountsToUpdate = new Map<Id, Account>();
        List<Financial_Account__c> finAccountsToUpdate = new List<Financial_Account__c>();
        
        for (Integer i = 0; i < casesToInsert.size(); i++) {
            Case insertedCase = casesToInsert[i];
            ServiceRequest req = requestMap.get(i);
            
            // Link Uploaded Documents
            if (req.uploadedDocumentIds != null && !req.uploadedDocumentIds.isEmpty()) {
                for (Id docId : req.uploadedDocumentIds) {
                    cdlsToInsert.add(new ContentDocumentLink(
                        ContentDocumentId = docId,
                        LinkedEntityId = insertedCase.Id,
                        ShareType = 'V'
                    ));
                }
            }
            
            // Handle Account Closure (Death)
            if (req.serviceType == 'Account Closure' && req.closureReason == 'Death') {
                accountsToUpdate.put(req.primaryOwnerId, new Account(
                    Id = req.primaryOwnerId,
                    Date_of_Death__c = req.dateOfDeath
                    
                ));
            }
            
            // Handle Order Tickets for DMS
            if (req.serviceType == 'Manage DMS Instructions') {
                ticketsToInsert.add(buildOrderTicket(insertedCase.Id, req));
            }
            
            // Handle Financial Account updates for Change Management Style
            if (req.serviceType == 'Change Management Style' && String.isNotBlank(req.newManagementStyle)) {
                finAccountsToUpdate.add(new Financial_Account__c(
                    Id = req.financialAccountId,
                    Managed_Account_Platform__c = req.newManagementStyle
                ));
            }
        }
        
        if (!cdlsToInsert.isEmpty()) insert cdlsToInsert;
        if (!ticketsToInsert.isEmpty()) insert ticketsToInsert;
        if (!accountsToUpdate.isEmpty()) update accountsToUpdate.values();
        if (!finAccountsToUpdate.isEmpty()) update finAccountsToUpdate;
    }
    
    private static Case buildBaseCase(ServiceRequest req) {
        return new Case(
            Origin = 'Wizard',
            Status = 'New',
            RecordTypeId = req.recordTypeId,
            Wizard_Financial_Account__c = req.financialAccountId,
            FinServ__Household__c = req.householdId,
            AccountId = req.householdId,
            ContactId = req.personContactId,
            Financial_Advisor_Team__c = req.advisorTeam,
            Incomplete_Record__c = false,
            Flow_Interview_ID__c = req.flowInterviewGuid
        );
    }
    
    private static Case applyAdditionalFundingRules(Case c, ServiceRequest req) {
        c.Subject = 'Additional Funding';
        c.Type = 'Additional Funding';
        c.Description = 'This Financial Account was recently serviced (Additional Funding).';
        return c;
    }
    
    private static Case applyTPMMRules(Case c, ServiceRequest req) {
        c.Subject = 'Third Party Money Movement';
        c.Type = 'Third Party Money Movement';
        c.Description = 'This Financial Account was recently serviced (Third Party Money Movement). Please review the documentation attached to this Case. Further documentation can also be found on the Household.';
        c.Needs_Principal_Review__c = true;
        return c;
    }
    
    private static Case applyAccountClosureRules(Case c, ServiceRequest req) {
        c.Subject = 'Account Closure - ' + req.closureReason;
        c.Type = 'Account Closure';
        c.Description = 'Please review all documentation and ensure that all necessary changes are made for this Account Closure.';
        c.Account_Closure_Reason__c = req.closureReason;
        c.Account_Closure_End_Date__c = req.closureEndDate;
        c.Account_Closure_Additional_Information__c = req.closureAdditionalInfo;
        c.Account_Closure_Explanation__c = req.closureExplanation;
        return c;
    }
    
    private static Case applyDMSInstructionRules(Case c, ServiceRequest req) {
        c.Management_Style__c = 'DMS';
        c.Order_Tickets__c = true;
        
        switch on req.subServiceType {
            when 'Update Trade Instructions' {
                c.Subject = 'Update Trade Instructions for ' + req.financialAccountName;
                c.Type = 'Update DMS Instructions';
                c.Description = 'Update Trade Instructions.';
                
                if (req.isBondLadder) c.Bond_Ladder__c = true;
                if (req.isSTCM) c.STCM__c = true;
            }
            when 'Raise Cash' {
                c.Subject = 'Raise Cash for ' + req.financialAccountName;
                c.Type = 'DMS - Raise Cash';
                c.Description = 'Raise Cash';
            }
            when 'Instructions for Future Deposit' {
                c.Subject = 'Instructions for Future Deposit for ' + req.financialAccountName;
                c.Type = 'DMS - Instructions for Future Deposit';
                c.Description = 'Instructions for Future Deposit';
            }
            when 'Add/Remove Systematic Withdrawals' {
                c.Subject = 'Add/Remove Systematic Withdrawals for ' + req.financialAccountName;
                c.Type = 'DMS - Add/Remove Systematic Withdrawals';
                c.Description = 'Add/Remove Systematic Withdrawals';
            }
            when 'Other' {
                c.Subject = 'DMS Request for ' + req.financialAccountName;
                c.Type = 'DMS - Other';
                c.Description = 'Other DMS Request';
            }
        }
        return c;
    }
    
    private static Case applyChangeManagementRules(Case c, ServiceRequest req) {
        c.Previous_Management_Style__c = req.currentManagedPlatform;
        c.Management_Style__c = req.newManagementStyle;
        c.Type = 'Change Management Style';
        c.Subject = 'Change Management Style';
        c.Description = 'Change Management Style to ' + req.newManagementStyle + '.';
        
        if (req.newManagementStyle.contains('DMS')) {
            c.Order_Tickets__c = true;
        }
        return c;
    }
    
    private static Order_Ticket__c buildOrderTicket(Id caseId, ServiceRequest req) {
        Order_Ticket__c ticket = new Order_Ticket__c(
            Case__c = caseId,
            Wizard_Financial_Account__c = req.financialAccountId,
            Flow_Interview_ID__c = req.flowInterviewGuid,
            Incomplete_Record__c = false
        );
        
        switch on req.subServiceType {
            when 'Raise Cash' {
                ticket.Type_of_Request__c = 'Raise Cash';
                ticket.Amount__c = req.requestAmount;
                ticket.Method_of_Cash_Raise__c = req.methodToAllocate;
                ticket.Additional_Details__c = req.additionalDetails;
            }
            when 'Instructions for Future Deposit' {
                ticket.Type_of_Request__c = 'Instructions for Future Deposit';
                ticket.Amount__c = req.requestAmount;
                ticket.Method_to_Allocate__c = req.methodToAllocate;
                ticket.Additional_Details__c = req.additionalDetails;
            }
            when 'Add/Remove Systematic Withdrawals' {
                ticket.Type_of_Request__c = (req.addOrRemove == 'Add') ? 'Add Systematic Withdrawal' : 'Remove Systematic Withdrawal';
                ticket.Amount__c = req.requestAmount;
                ticket.Frequency__c = req.frequency;
                ticket.Date_of_First_Withdrawal__c = req.firstWithdrawalDate;
                ticket.End_Date__c = req.expectedEndDate;
                ticket.Additional_Details__c = req.additionalDetails;
            }
            when 'Other' {
                ticket.Type_of_Request__c = 'Other';
                ticket.Additional_Details__c = req.additionalDetails;
            }
        }
        return ticket;
    }
}