unpackaged/main/default/objects/Account/fields/Trust_Type__c.field-meta.xml
<CustomField>
    <fullName>Trust_Type__c</fullName>
    <label>Trust Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joint (Community Property, JTWROS, Tenants in Common, Tenants in the Entirety)</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
            <value>
                <fullName>UTMA/UGMA</fullName>
            </value>
            <value>
                <fullName>Corporation (C or S)</fullName>
            </value>
            <value>
                <fullName>Estate</fullName>
            </value>
            <value>
                <fullName>Other Non-Trust Fiduciary (Conservatorship or Guardianship)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Account_Account_Relationship__c/Account_Account_Relationship__c.object-meta.xml
<CustomObject>
    <description>A relationship between two accounts, such as a Household and a Business account.</description>
    <label>Account Account Relationship</label>
    <nameField>
        <displayFormat>AAR-{0000}</displayFormat>
        <label>Account Account Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relationshipa</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Account Relationshipa</relationshipLabel>
    <relationshipName>Account_Account_Relationshipa</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether the relationship is active.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Reciprocal_Role__c.field-meta.xml
<CustomField>
    <fullName>Reciprocal_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Reciprocal_Role__c for member account relationships on the map.</description>
    <label>Role</label>
    <referenceTo>Reciprocal_Role__c</referenceTo>
    <relationshipLabel>Account Account Relationshipa</relationshipLabel>
    <relationshipName>Account_Account_Relationshipa</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Account Relationship (Related Account)</relationshipLabel>
    <relationshipName>Account_Account_Relationship1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attorney</fullName>
            </value>
            <value>
                <fullName>Aunt / Uncle</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Client Entity</fullName>
            </value>
            <value>
                <fullName>CPA</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Ex-Spouse</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Grandchild</fullName>
            </value>
            <value>
                <fullName>Grandparent</fullName>
            </value>
            <value>
                <fullName>In-Law</fullName>
            </value>
            <value>
                <fullName>Life Partner</fullName>
            </value>
            <value>
                <fullName>Nephew</fullName>
            </value>
            <value>
                <fullName>Niece / Nephew</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>529 Beneficiary</fullName>
            </value>
            <value>
                <fullName>Account Beneficiary</fullName>
            </value>
            <value>
                <fullName>Authorized Person</fullName>
            </value>
            <value>
                <fullName>Beneficial Owner</fullName>
            </value>
            <value>
                <fullName>Control Person</fullName>
            </value>
            <value>
                <fullName>Custodian (Minor)</fullName>
            </value>
            <value>
                <fullName>Executor / Personal Representative</fullName>
            </value>
            <value>
                <fullName>Guardian / Conservator</fullName>
            </value>
            <value>
                <fullName>Plan Administrator</fullName>
            </value>
            <value>
                <fullName>Plan Participant</fullName>
            </value>
            <value>
                <fullName>Power of Attorney</fullName>
            </value>
            <value>
                <fullName>Trust Beneficiary</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Trusted Contact</fullName>
            </value>
            <value>
                <fullName>Grantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Account_Relationship__c/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Business</label>
</RecordType>

unpackaged/main/default/objects/Account_Account_Relationship__c/recordTypes/Fiduciary_Legal.recordType-meta.xml
<RecordType>
    <fullName>Fiduciary_Legal</fullName>
    <active>true</active>
    <label>Fiduciary / Regulatory</label>
</RecordType>

unpackaged/main/default/objects/Account_Account_Relationship__c/recordTypes/Household.recordType-meta.xml
<RecordType>
    <fullName>Household</fullName>
    <active>true</active>
    <label>Household</label>
</RecordType>

unpackaged/main/default/objects/Account_Account_Relationship__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producing</fullName>
            </value>
            <value>
                <fullName>Non-Producing</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
                <isActive>false</isActive>
                <label>Advisor</label>
            </value>
            <value>
                <fullName>Non-Registered Support Staff</fullName>
                <isActive>false</isActive>
                <label>Non-Registered Support Staff</label>
            </value>
            <value>
                <fullName>Registered Support Staff</fullName>
                <isActive>false</isActive>
                <label>Registered Support Staff</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/Reciprocal_Role__c/Reciprocal_Role__c.object-meta.xml
<CustomObject>
    <label>Reciprocal Role</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Reciprocal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Reciprocal_Role__c/recordTypes/Fiduciary_Legal.recordType-meta.xml
<RecordType>
    <fullName>Fiduciary_Legal</fullName>
    <active>true</active>
    <label>Fiduciary / Regulatory</label>
</RecordType>

unpackaged/main/default/objects/Reciprocal_Role__c/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <label>Other</label>
</RecordType>

unpackaged/main/default/classes/ArcAccountRelationshipsControllerTest.cls
@IsTest
private class ArcAccountRelationshipsControllerTest {
  /**
   * Account.Type on every test account: the Type_OR_Classification_Required
   * validation rule (activated 2026-09-02) rejects a Business, Trust,
   * Retirement Plan or person account that carries neither a Type nor a
   * Classification, which is what broke this class's setup.
   */
  private static final String ACCOUNT_TYPE = 'Prospect';

  @TestSetup
  static void setup() {
    Id trustRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('Trust')
      .getRecordTypeId();
    Id businessRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('Business')
      .getRecordTypeId();
    Id individualRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('Diversify_Related_Person')
      .getRecordTypeId();
    Id householdRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('Household')
      .getRecordTypeId();
    Id retirementPlanRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get('Retirement_Plan')
      .getRecordTypeId();
    Id fiduciaryRecordTypeId = Schema.SObjectType.Account_Account_Relationship__c.getRecordTypeInfosByDeveloperName()
      .get('Fiduciary_Legal')
      .getRecordTypeId();
    Id householdRelationshipRecordTypeId = Schema.SObjectType.Account_Account_Relationship__c.getRecordTypeInfosByDeveloperName()
      .get('Household')
      .getRecordTypeId();

    Account trustAccount = new Account(Type = ACCOUNT_TYPE, Name = 'Test Trust', RecordTypeId = trustRecordTypeId);
    Account estateAccount = new Account(
      Type = ACCOUNT_TYPE,
      Name = 'Test Estate',
      RecordTypeId = trustRecordTypeId,
      Trust_Type__c = 'Estate'
    );
    Account businessAccount = new Account(Type = ACCOUNT_TYPE, Name = 'Test Business', RecordTypeId = businessRecordTypeId);
    // Diversify_Related_Person is a true Person Account record type -- Name
    // is computed from First/Last, not directly settable.
    Account individualAccount = new Account(
      Type = ACCOUNT_TYPE,
      FirstName = 'Test',
      LastName = 'Individual',
      RecordTypeId = individualRecordTypeId
    );
    Account householdAccount = new Account(Type = ACCOUNT_TYPE, Name = 'Test Household', RecordTypeId = householdRecordTypeId);
    Account retirementPlanAccount = new Account(
      Type = ACCOUNT_TYPE,
      Name = 'Test Retirement Plan',
      RecordTypeId = retirementPlanRecordTypeId
    );
    // The "related person" stand-ins only need to exist and have a Name --
    // their own record type isn't what this test is checking -- so these
    // use the plain Business type rather than fighting Person Account's
    // First/Last-only Name.
    Account trusteePerson = new Account(Type = ACCOUNT_TYPE, Name = 'Trustee Person', RecordTypeId = businessRecordTypeId);
    Account grantorPerson = new Account(Type = ACCOUNT_TYPE, Name = 'Grantor Person', RecordTypeId = businessRecordTypeId);
    Account executorPerson = new Account(Type = ACCOUNT_TYPE, Name = 'Executor Person', RecordTypeId = businessRecordTypeId);
    Account beneficialOwnerPerson = new Account(
      Type = ACCOUNT_TYPE,
      Name = 'Beneficial Owner Person',
      RecordTypeId = businessRecordTypeId
    );
    Account trustedContactPerson = new Account(
      Type = ACCOUNT_TYPE,
      Name = 'Trusted Contact Person',
      RecordTypeId = businessRecordTypeId
    );

    insert new List<Account>{
      trustAccount,
      estateAccount,
      businessAccount,
      individualAccount,
      householdAccount,
      retirementPlanAccount,
      trusteePerson,
      grantorPerson,
      executorPerson,
      beneficialOwnerPerson,
      trustedContactPerson
    };

    // The controller reads a relationship's role off Reciprocal_Role__r.Role__c
    // (the Relationship Map's catalog), so each fiduciary row below points at a
    // catalog entry spelled the way the controller's synonym table expects.
    Reciprocal_Role__c trusteeRole = new Reciprocal_Role__c(Role__c = 'Trustee');
    Reciprocal_Role__c grantorRole = new Reciprocal_Role__c(Role__c = 'Grantor');
    Reciprocal_Role__c executorRole = new Reciprocal_Role__c(Role__c = 'Executor / Personal Representative');
    Reciprocal_Role__c beneficialOwnerRole = new Reciprocal_Role__c(Role__c = 'Beneficial Owner');
    Reciprocal_Role__c trustedContactRole = new Reciprocal_Role__c(Role__c = 'Trusted Contact');
    insert new List<Reciprocal_Role__c>{
      trusteeRole,
      grantorRole,
      executorRole,
      beneficialOwnerRole,
      trustedContactRole
    };

    insert new List<Account_Account_Relationship__c>{
      new Account_Account_Relationship__c(
        Account__c = trustAccount.Id,
        Related_Account__c = trusteePerson.Id,
        Reciprocal_Role__c = trusteeRole.Id,
        RecordTypeId = fiduciaryRecordTypeId,
        Active__c = true
      ),
      new Account_Account_Relationship__c(
        Account__c = trustAccount.Id,
        Related_Account__c = grantorPerson.Id,
        Reciprocal_Role__c = grantorRole.Id,
        RecordTypeId = fiduciaryRecordTypeId,
        Active__c = true
      ),
      new Account_Account_Relationship__c(
        Account__c = estateAccount.Id,
        Related_Account__c = executorPerson.Id,
        Reciprocal_Role__c = executorRole.Id,
        RecordTypeId = fiduciaryRecordTypeId,
        Active__c = true
      ),
      new Account_Account_Relationship__c(
        Account__c = businessAccount.Id,
        Related_Account__c = beneficialOwnerPerson.Id,
        Reciprocal_Role__c = beneficialOwnerRole.Id,
        RecordTypeId = fiduciaryRecordTypeId,
        Active__c = true
      ),
      new Account_Account_Relationship__c(
        Account__c = individualAccount.Id,
        Related_Account__c = trustedContactPerson.Id,
        Reciprocal_Role__c = trustedContactRole.Id,
        RecordTypeId = fiduciaryRecordTypeId,
        Active__c = true
      ),
      // Inactive rows and rows on other record types must never surface.
      new Account_Account_Relationship__c(
        Account__c = trustAccount.Id,
        Related_Account__c = trustedContactPerson.Id,
        Reciprocal_Role__c = trusteeRole.Id,
        RecordTypeId = fiduciaryRecordTypeId,
        Active__c = false
      ),
      // Household membership: household -> member, record type Household, no role.
      new Account_Account_Relationship__c(
        Account__c = householdAccount.Id,
        Related_Account__c = individualAccount.Id,
        RecordTypeId = householdRelationshipRecordTypeId,
        Active__c = true
      ),
      new Account_Account_Relationship__c(
        Account__c = householdAccount.Id,
        Related_Account__c = businessAccount.Id,
        RecordTypeId = householdRelationshipRecordTypeId,
        Active__c = true
      ),
      new Account_Account_Relationship__c(
        Account__c = householdAccount.Id,
        Related_Account__c = trustAccount.Id,
        RecordTypeId = householdRelationshipRecordTypeId,
        Active__c = true
      ),
      // An inactive membership, and a fiduciary row hung off the household,
      // must both stay out of the household's member groups.
      new Account_Account_Relationship__c(
        Account__c = householdAccount.Id,
        Related_Account__c = estateAccount.Id,
        RecordTypeId = householdRelationshipRecordTypeId,
        Active__c = false
      ),
      new Account_Account_Relationship__c(
        Account__c = householdAccount.Id,
        Related_Account__c = trustedContactPerson.Id,
        RecordTypeId = fiduciaryRecordTypeId,
        Active__c = true
      )
    };
  }

  @IsTest
  static void returnsTrusteeAndGrantorForTrust() {
    Account trustAccount = [SELECT Id FROM Account WHERE Name = 'Test Trust' LIMIT 1];

    Test.startTest();
    ArcAccountRelationshipsController.RelationshipsResult result = ArcAccountRelationshipsController.getRelationships(
      trustAccount.Id
    );
    Test.stopTest();

    Assert.areEqual('Trust', result.category);
    Assert.areEqual(2, result.groups.size());
    Assert.areEqual('Trustee', result.groups[0].label);
    Assert.areEqual(1, result.groups[0].rows.size(), 'inactive row must be excluded');
    Assert.areEqual('Trustee Person', result.groups[0].rows[0].relatedAccountName);
    Assert.areEqual('Grantor', result.groups[1].label);
    Assert.areEqual(1, result.groups[1].rows.size());
    Assert.areEqual('Grantor Person', result.groups[1].rows[0].relatedAccountName);
  }

  @IsTest
  static void returnsExecutorForEstate() {
    Account estateAccount = [SELECT Id FROM Account WHERE Name = 'Test Estate' LIMIT 1];

    Test.startTest();
    ArcAccountRelationshipsController.RelationshipsResult result = ArcAccountRelationshipsController.getRelationships(
      estateAccount.Id
    );
    Test.stopTest();

    Assert.areEqual('Estate', result.category);
    Assert.areEqual(1, result.groups.size());
    Assert.areEqual('Executor', result.groups[0].label);
    Assert.areEqual(1, result.groups[0].rows.size());
    Assert.areEqual('Executor Person', result.groups[0].rows[0].relatedAccountName);
  }

  @IsTest
  static void returnsBusinessBucketsIncludingEmptyOnes() {
    Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Business' LIMIT 1];

    Test.startTest();
    ArcAccountRelationshipsController.RelationshipsResult result = ArcAccountRelationshipsController.getRelationships(
      businessAccount.Id
    );
    Test.stopTest();

    Assert.areEqual('Business', result.category);
    Assert.areEqual(3, result.groups.size(), 'Control Person, Beneficial Owner, Authorized Person, always all three');

    Map<String, ArcAccountRelationshipsController.RelationshipGroup> byLabel = new Map<String, ArcAccountRelationshipsController.RelationshipGroup>();
    for (ArcAccountRelationshipsController.RelationshipGroup relationshipGroup : result.groups) {
      byLabel.put(relationshipGroup.label, relationshipGroup);
    }

    Assert.areEqual(1, byLabel.get('Beneficial Owner').rows.size());
    Assert.areEqual(0, byLabel.get('Control Person').rows.size(), 'empty bucket must still be returned');
    Assert.areEqual(0, byLabel.get('Authorized Person').rows.size());
  }

  @IsTest
  static void returnsTrustedContactForIndividual() {
    Account individualAccount = [SELECT Id FROM Account WHERE Name = 'Test Individual' LIMIT 1];

    Test.startTest();
    ArcAccountRelationshipsController.RelationshipsResult result = ArcAccountRelationshipsController.getRelationships(
      individualAccount.Id
    );
    Test.stopTest();

    Assert.areEqual('Individual', result.category);
    Assert.areEqual(1, result.groups.size());
    Assert.areEqual('Trusted Contact', result.groups[0].label);
    Assert.areEqual(1, result.groups[0].rows.size());
  }

  @IsTest
  static void returnsMembersGroupedByTypeForHousehold() {
    Account householdAccount = [SELECT Id FROM Account WHERE Name = 'Test Household' LIMIT 1];

    Test.startTest();
    ArcAccountRelationshipsController.RelationshipsResult result = ArcAccountRelationshipsController.getRelationships(
      householdAccount.Id
    );
    Test.stopTest();

    Assert.areEqual('Household', result.category);
    Assert.areEqual(4, result.groups.size(), 'Members, Businesses, Trusts & Estates, Retirement Plans, always all four');
    Assert.areEqual('Members', result.groups[0].label);
    Assert.areEqual(1, result.groups[0].rows.size());
    Assert.areEqual('Test Individual', result.groups[0].rows[0].relatedAccountName);
    Assert.areEqual('Businesses', result.groups[1].label);
    Assert.areEqual(1, result.groups[1].rows.size(), 'the fiduciary row on the household is not membership');
    Assert.areEqual('Test Business', result.groups[1].rows[0].relatedAccountName);
    Assert.areEqual('Trusts & Estates', result.groups[2].label);
    Assert.areEqual(1, result.groups[2].rows.size(), 'inactive membership must be excluded');
    Assert.areEqual('Test Trust', result.groups[2].rows[0].relatedAccountName);
    Assert.areEqual('Retirement Plans', result.groups[3].label);
    Assert.areEqual(0, result.groups[3].rows.size(), 'empty group must still be returned');
  }

  @IsTest
  static void returnsEmptyForUnsupportedRecordTypeAndNullOrMissingId() {
    Account retirementPlanAccount = [SELECT Id FROM Account WHERE Name = 'Test Retirement Plan' LIMIT 1];

    Test.startTest();
    ArcAccountRelationshipsController.RelationshipsResult unsupportedResult = ArcAccountRelationshipsController.getRelationships(
      retirementPlanAccount.Id
    );
    ArcAccountRelationshipsController.RelationshipsResult nullResult = ArcAccountRelationshipsController.getRelationships(
      null
    );
    Test.stopTest();

    Assert.areEqual('', unsupportedResult.category);
    Assert.isTrue(unsupportedResult.groups.isEmpty());
    Assert.areEqual('', nullResult.category);
    Assert.isTrue(nullResult.groups.isEmpty());
  }
}