unpackaged/main/default/objects/Case/fields/ASAA_as_a_of_Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>ASAA_as_a_of_Net_Worth__c</fullName>
    <description>All Securitized Alt Investments (as a % of Net Worth)</description>
    <label>ASAA as a % of Net Worth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EP_Total_as_of_Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>EP_Total_as_of_Net_Worth__c</fullName>
    <description>Energy Programs Total Amount in Asset Class as a % of Net Worth.</description>
    <label>EP Total as % of Net Worth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/EP_Total_including_Today__c.field-meta.xml
<CustomField>
    <fullName>EP_Total_including_Today__c</fullName>
    <description>Energy Programs Total $ Amount in Asset Class (including today&#39;s purchase)</description>
    <label>EP Total $ including Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/IF_Total_as_of_Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>IF_Total_as_of_Net_Worth__c</fullName>
    <description>Interval Funds Total Amount in Asset Class as a % of Net Worth.</description>
    <label>IF Total as % of Net Worth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/IF_Total_including_Today__c.field-meta.xml
<CustomField>
    <fullName>IF_Total_including_Today__c</fullName>
    <description>Interval Funds Total $ Amount in Asset Class (including today&#39;s purchase)</description>
    <label>IF Total $ including Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PC_Total_as_of_Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>PC_Total_as_of_Net_Worth__c</fullName>
    <description>Private Credit Total Amount is Asset Class as a % of Net Worth.</description>
    <label>PC Total as % of Net Worth</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PC_Total_including_Today__c.field-meta.xml
<CustomField>
    <fullName>PC_Total_including_Today__c</fullName>
    <description>Private Credit Total $ Amount in Asset Class (including Today&#39;s purchase)</description>
    <label>PC Total $ including Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PE_Total_as_of_Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>PE_Total_as_of_Net_Worth__c</fullName>
    <description>Private Equity Total Amount in Asset Class as a % of Net Worth.</description>
    <label>PE Total as % of Net Worth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/PE_Total_including_Today__c.field-meta.xml
<CustomField>
    <fullName>PE_Total_including_Today__c</fullName>
    <description>Private Equity Total $ Amount in Asset Class (including today&#39;s purchase)</description>
    <label>PE Total $ including Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/SN_Total_as_of_Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>SN_Total_as_of_Net_Worth__c</fullName>
    <description>Structured Notes Total Amount in Asset Class as a % of Net Worth.</description>
    <label>SN Total as % of Net Worth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/SN_Total_including_Today__c.field-meta.xml
<CustomField>
    <fullName>SN_Total_including_Today__c</fullName>
    <description>Structured Notes Total $ Amount in Asset Class (including today&#39;s purchases)</description>
    <label>SN Total $ including Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/SREP_Total_as_of_Net_Worth__c.field-meta.xml
<CustomField>
    <fullName>SREP_Total_as_of_Net_Worth__c</fullName>
    <description>Securitized Private Real Estate Total Amount in Asset Class as a % of Net Worth.</description>
    <label>SREP Total as % of Net Worth</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/SREP_Total_including_Today__c.field-meta.xml
<CustomField>
    <fullName>SREP_Total_including_Today__c</fullName>
    <description>Securitized Private Real Estate Total $ Amount in Asset Class (including today&#39;s purchase)</description>
    <label>SREP Total $ including Today</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/ConcentrationTableHelperTest.cls
@IsTest
public class ConcentrationTableHelperTest {
    @IsTest
    private static void getCaseValues_Test(){ 
        Test.startTest();
        Case caseRecord =  new case(SREP_Total_including_Today__c = 0 , PE_Total_including_Today__c= 0, 
                                    PC_Total_including_Today__c= 0, IF_Total_including_Today__c= 0, EP_Total_including_Today__c= 0, 
                                    SN_Total_including_Today__c= 0, SREP_Total_as_of_Net_Worth__c= 0, PE_Total_as_of_Net_Worth__c= 0, 
                                    PC_Total_as_of_Net_Worth__c= 0, IF_Total_as_of_Net_Worth__c= 0, EP_Total_as_of_Net_Worth__c= 0, 
                                    SN_Total_as_of_Net_Worth__c= 0, ASAA_as_a_of_Net_Worth__c= 0);              
        insert caseRecord;    
        Case caseInserted =  ConcentrationTableHelper.getCaseValues(caseRecord.Id);
        Test.stopTest();
        Assert.areNotEqual(null, caseInserted,'Case list should be have one record');
        
    }
    
}