unpackaged/main/default/objects/Case/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Wizard_Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Producing</fullName>
            </value>
            <value>
                <fullName>Non-Producing</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
            </value>
            <value>
                <fullName>Advisor</fullName>
                <isActive>false</isActive>
                <label>Advisor</label>
            </value>
            <value>
                <fullName>Non-Registered Support Staff</fullName>
                <isActive>false</isActive>
                <label>Non-Registered Support Staff</label>
            </value>
            <value>
                <fullName>Registered Support Staff</fullName>
                <isActive>false</isActive>
                <label>Registered Support Staff</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/Financial_Advisor_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team Member</label>
    <nameField>
        <displayFormat>FATM-{0000}</displayFormat>
        <label>Financial Advisor Team Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Advisor Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Financial Advisor Team Members</relationshipLabel>
    <relationshipName>Financial_Advisor_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial Advisor</fullName>
            </value>
            <value>
                <fullName>Branch Member</fullName>
            </value>
            <value>
                <fullName>CSA</fullName>
            </value>
            <value>
                <fullName>Associate Advisor</fullName>
            </value>
            <value>
                <fullName>Staff</fullName>
                <isActive>false</isActive>
                <label>Staff</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Task_Comment__c/Task_Comment__c.object-meta.xml
<CustomObject>
    <label>Task Comment</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Task Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Task_Comment__c/fields/CommentBody__c.field-meta.xml
<CustomField>
    <fullName>CommentBody__c</fullName>
    <label>Body</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Task_Comment__c/fields/Task_ID__c.field-meta.xml
<CustomField>
    <fullName>Task_ID__c</fullName>
    <label>Task ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Task_Comment_TriggerHandlerTest.cls
@isTest
public class Task_Comment_TriggerHandlerTest {

    /*@testSetup
    private static void setup(){
        Wizard_Financial_Account__c testWFA = new Wizard_Financial_Account__c(Name = 'Test Financial Account');
        insert testWFA;
        
        Financial_Advisor_Team__c testFAT = new Financial_Advisor_Team__c(Name = 'Test FAT');
        insert testFAT;
        
        List<Account> accList = new List<Account>();
        accList.add(new Account(Name = 'Test Account', Financial_Advisor_Team__c = testFAT.Id));
        accList.add(new Account(Name = 'Test Account 2'));
        insert accList;
        
        Contact con = new Contact(LastName = 'Test', Email = 'test.test@dfpg.com');
        insert con;
        
        
        Financial_Advisor_Team_Member__c fatm = new Financial_Advisor_Team_Member__c(Role__c = 'Financial Advisor', Active__c = true, Financial_Advisor_Team__c = testFAT.Id);
        //insert fatm;
     
    }
    
    @isTest
    public static void testTaskComment(){
        Case newCase = new Case(Origin = 'Web', Status = 'New');
        insert newCase;
        Task newTask = new Task(WhatId = newCase.Id, Status = 'New');
        insert newTask;
        Task_Comment__c taskComment = new Task_Comment__c(Task_Id__c = newTask.Id, CommentBody__c = 'test');
        
        Test.startTest();
        insert taskComment;
        Test.stopTest();
        
        List<CaseComment> caseComments = [SELECT Id FROM CaseComment WHERE ParentId = :newCase.Id LIMIT 1];
        Assert.areEqual(1, caseComments.size());
        
        //For coverage
        delete taskComment;
        undelete taskComment;
        
    }
    
    @isTest
    public static void testTaskCommentUpdate(){
        Case newCase = new Case(Origin = 'Web', Status = 'New');
        insert newCase;
        Task newTask = new Task(WhatId = newCase.Id, Status = 'New');
        insert newTask;
        Task_Comment__c taskComment = new Task_Comment__c(Task_Id__c = newTask.Id, CommentBody__c = 'test');
        insert taskComment;
        
        Test.startTest();
        Task_Comment__c tc = [SELECT Id, CommentBody__c FROM Task_Comment__c LIMIT 1];
        tc.CommentBody__c = 'Test 2';
        update tc;
        Test.stopTest();
        
        List<CaseComment> caseComments = [SELECT Id, CommentBody FROM CaseComment WHERE ParentId = :newCase.Id LIMIT 1];
        Assert.areEqual('Test 2', caseComments[0].CommentBody);
        
    }
    
    @isTest
    private static void getExistingRecordsTest(){
        
        Case newCase = new Case(Origin = 'Web', Status = 'New');
        insert newCase;
        Task newTask = new Task(WhatId = newCase.Id, Status = 'New');
        insert newTask;
        Task_Comment__c taskComment = new Task_Comment__c(Task_Id__c = newTask.Id, CommentBody__c = 'test');
        insert taskComment;
        
        Test.startTest();
        List<Task_Comment__c> lstRecords = TaskCommentController.getComments(newTask.Id);
        Test.stopTest();
        Assert.isTrue(lstRecords.size() == 1, 'Method should return list.');
    }*/
}