unpackaged/main/default/objects/Case/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household New Field</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Household New Field)</relationshipLabel>
    <relationshipName>Cases5</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/Notification_Log__c.object-meta.xml
<CustomObject>
    <label>Notification Log</label>
    <nameField>
        <displayFormat>NOTIF-LOG-{000000}</displayFormat>
        <label>Notification Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Log__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Change_Context__c.field-meta.xml
<CustomField>
    <fullName>Change_Context__c</fullName>
    <label>Change Context</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>In_App</fullName>
                <label>In App</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <isActive>false</isActive>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Zoom</fullName>
                <isActive>false</isActive>
                <label>Zoom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Delivered_At__c.field-meta.xml
<CustomField>
    <fullName>Delivered_At__c</fullName>
    <label>Delivered At</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Delivery_Attempt_Count__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Attempt_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Delivery Attempt Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>Digest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Notification_Rule__c.field-meta.xml
<CustomField>
    <fullName>Notification_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notification Rule</label>
    <referenceTo>Notification_Rule__c</referenceTo>
    <relationshipLabel>Applied Notification Logs</relationshipLabel>
    <relationshipName>Applied_Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recipient</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Notification Logs</relationshipLabel>
    <relationshipName>Notification_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Record_Id__c</fullName>
    <label>Source Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <label>Source Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Suppressed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Log__c/fields/Target_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Target_Record_Id__c</fullName>
    <label>Target Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/Notification_Rule__c.object-meta.xml
<CustomObject>
    <label>Notification Rule</label>
    <nameField>
        <displayFormat>NR-{00000}</displayFormat>
        <label>Notification Rule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Notification_Rule__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>In_App</fullName>
                <label>In App</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <isActive>false</isActive>
                <label>SMS</label>
            </value>
            <value>
                <fullName>Zoom</fullName>
                <isActive>false</isActive>
                <label>Zoom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Digest_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Digest_Cadence__c</fullName>
    <label>Digest Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Hourly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Digest_Frequency_Hour__c.field-meta.xml
<CustomField>
    <fullName>Digest_Frequency_Hour__c</fullName>
    <description>Hour of day (0-23) when hourly digest delivery should run.</description>
    <label>Digest Frequency Hour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>12:00 AM</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>1:00 AM</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2:00 AM</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>3:00 AM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>4:00 AM</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>5:00 AM</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>6:00 AM</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>7:00 AM</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8:00 AM</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>9:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10:00 AM</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11:00 AM</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12:00 PM</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>1:00 PM</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>2:00 PM</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>3:00 PM</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>4:00 PM</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>5:00 PM</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>6:00 PM</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>7:00 PM</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>8:00 PM</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>9:00 PM</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>10:00 PM</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>11:00 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
                <default>true</default>
                <label>Immediate</label>
            </value>
            <value>
                <fullName>Digest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Notification_Rule__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notification Rules</relationshipLabel>
    <relationshipName>Notification_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/NotificationDigestRuleBatchTest.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-06-17
 */
@IsTest
private class NotificationDigestRuleBatchTest {
  @IsTest
  static void batchPublishesCenterEventsForMatchingDigestRules() {
    NotificationCenterEventPublisher.resetForTest();
    NotificationTestDataFactory.NotificationTestContext context = NotificationTestDataFactory.createHouseholdWithRecipient();
    Notification_Rule__c rule = NotificationTestDataFactory.createUserPreference(
      NotificationConstants.OBJECT_TYPE_CASE,
      context.recipientUser.Id,
      NotificationConstants.CHANNEL_EMAIL,
      NotificationConstants.FREQUENCY_DIGEST
    );
    rule.Digest_Cadence__c = NotificationConstants.DIGEST_FREQUENCY_DAILY;
    rule.Digest_Frequency_Hour__c = NotificationDigestTimezoneService.currentDigestHourValue();
    NotificationTestDataFactory.updateRecord(rule);

    Case caseRecord = new Case(
      Subject = 'Digest batch case',
      AccountId = context.household.Id
    );
    NotificationTestDataFactory.insertRecord(caseRecord);

    Notification_Log__c logRecord = NotificationTestDataFactory.createLogNotification(
      context.recipientUser.Id,
      context.household.Id,
      NotificationConstants.OBJECT_TYPE_CASE,
      NotificationConstants.STATUS_QUEUED,
      NotificationConstants.CHANNEL_EMAIL,
      NotificationConstants.FREQUENCY_DIGEST,
      'Queued digest item',
      null,
      rule.Id
    );
    logRecord.Source_Record_Id__c = String.valueOf(caseRecord.Id);
    NotificationTestDataFactory.updateRecord(logRecord);

    List<NotificationDigestModels.DigestDeliveryRequest> deliveryRequests = NotificationDeliveryGroupingService.buildDeliveryRequestsForRuleIds(
      new Set<Id>{ rule.Id },
      NotificationConstants.DIGEST_FREQUENCY_DAILY
    );
    System.assert(
      !deliveryRequests.isEmpty(),
      'Expected digest delivery requests to be built for queued logs.'
    );
    NotificationCenterEventPublisher.publishDigestDeliveryGroups(deliveryRequests);
    System.assert(
      NotificationCenterEventPublisher.testPublishedEventCount > 0,
      'Expected digest delivery preparation to publish Notification Center Events.'
    );

    Test.startTest();
    Database.executeBatch(
      new NotificationDigestRuleBatch(NotificationConstants.DIGEST_FREQUENCY_DAILY),
      200
    );
    Test.stopTest();
  }

  @IsTest
  static void logScopedBatchEnqueuesDeliveryJobsForPreviewRows() {
    NotificationCenterEventPublisher.resetForTest();

    NotificationTestDataFactory.NotificationTestContext context = NotificationTestDataFactory.createHouseholdWithRecipient();
    Case caseRecord = createOwnedCase(context);
    Notification_Log__c logRecord = createDigestInAppLog(context, caseRecord.Id);
    logRecord.Status__c = NotificationConstants.STATUS_SENT;
    logRecord.Delivered_At__c = System.now();
    NotificationTestDataFactory.updateRecord(logRecord);

    NotificationLogDeliveryService.requeueForDebugDelivery(new List<Notification_Log__c>{ logRecord });
    logRecord = [
      SELECT Id, Status__c, Recipient__c, Channel__c, Source_Type__c
      FROM Notification_Log__c
      WHERE Id = :logRecord.Id
    ];
    System.assertEquals(NotificationConstants.STATUS_QUEUED, logRecord.Status__c);

    List<NotificationDigestModels.DigestDeliveryRequest> deliveryRequests = new List<NotificationDigestModels.DigestDeliveryRequest>{
      NotificationDeliveryGroupingService.buildDeliveryRequest(
        new List<Notification_Log__c>{ logRecord },
        NotificationConstants.DIGEST_FREQUENCY_DAILY,
        0,
        NotificationConstants.CHANNEL_IN_APP
      )
    };
    NotificationCenterEventPublisher.publishDigestDeliveryGroups(deliveryRequests);
    System.assert(
      NotificationCenterEventPublisher.testPublishedEventCount > 0,
      'Expected log-scoped digest delivery preparation to publish Notification Center Events.'
    );

    Test.startTest();
    Database.executeBatch(
      new NotificationDigestRuleBatch(
        NotificationConstants.DIGEST_FREQUENCY_DAILY,
        new List<Id>{ logRecord.Id }
      ),
      200
    );
    Test.stopTest();
  }

  @IsTest
  static void recordScopedBatchEnqueuesDeliveryJobsForSourceRecords() {
    NotificationCenterEventPublisher.resetForTest();

    NotificationTestDataFactory.NotificationTestContext context = NotificationTestDataFactory.createHouseholdWithRecipient();
    Case firstCase = createOwnedCase(context);
    Case secondCase = createOwnedCase(context);
    Notification_Log__c firstLog = createDigestInAppLog(context, firstCase.Id);
    Notification_Log__c secondLog = createDigestInAppLog(context, secondCase.Id);

    NotificationCenterEventPublisher.publishDigestDeliveryGroups(
      new List<NotificationDigestModels.DigestDeliveryRequest>{
        NotificationDeliveryGroupingService.buildDeliveryRequest(
          new List<Notification_Log__c>{ firstLog, secondLog },
          NotificationConstants.DIGEST_FREQUENCY_DAILY,
          0,
          NotificationConstants.CHANNEL_IN_APP
        )
      }
    );
    System.assert(
      NotificationCenterEventPublisher.testPublishedEventCount > 0,
      'Expected record-scoped digest delivery preparation to publish Notification Center Events.'
    );

    Test.startTest();
    Database.executeBatch(
      new NotificationDigestRuleBatch(
        NotificationConstants.DIGEST_FREQUENCY_DAILY,
        context.recipientUser.Id,
        NotificationConstants.OBJECT_TYPE_CASE,
        new List<Id>{ firstCase.Id, secondCase.Id }
      ),
      200
    );
    Test.stopTest();
  }

  @IsTest
  static void dailySchedulerStartsDigestBatch() {
    Test.startTest();
    new NotificationDigestDailyScheduler().execute(null);
    Test.stopTest();

    System.assertEquals(
      1,
      [SELECT COUNT() FROM AsyncApexJob WHERE JobType = 'BatchApex'],
      'Expected daily scheduler to start a batch job.'
    );
  }

  @IsTest
  static void weeklySchedulerStartsDigestBatch() {
    Test.startTest();
    new NotificationDigestWeeklyScheduler().execute(null);
    Test.stopTest();

    System.assertEquals(
      1,
      [SELECT COUNT() FROM AsyncApexJob WHERE JobType = 'BatchApex'],
      'Expected weekly scheduler to start a batch job.'
    );
  }

  @IsTest
  static void hourlySchedulerStartsDigestBatch() {
    Test.startTest();
    new NotificationDigestHourlyScheduler().execute(null);
    Test.stopTest();

    System.assertEquals(
      1,
      [SELECT COUNT() FROM AsyncApexJob WHERE JobType = 'BatchApex'],
      'Expected hourly scheduler to start a batch job.'
    );
  }

  @IsTest
  static void batchWithEmptyScopeCompletesWithoutErrors() {
    Test.startTest();
    Database.executeBatch(
      new NotificationDigestRuleBatch(NotificationConstants.DIGEST_FREQUENCY_WEEKLY),
      200
    );
    Test.stopTest();

    System.assert(true, 'Weekly digest batch should complete with empty scope.');
  }

  @IsTest
  static void batchConstructorWithRecipientScopeStartsBatchJob() {
    NotificationTestDataFactory.NotificationTestContext context = NotificationTestDataFactory.createHouseholdWithRecipient();
    Case caseRecord = createOwnedCase(context);
    createDigestInAppLog(context, caseRecord.Id);

    Test.startTest();
    Database.executeBatch(
      new NotificationDigestRuleBatch(
        NotificationConstants.DIGEST_FREQUENCY_DAILY,
        context.recipientUser.Id,
        NotificationConstants.OBJECT_TYPE_CASE,
        new List<Id>{ caseRecord.Id }
      ),
      200
    );
    Test.stopTest();

    System.assertEquals(
      1,
      [SELECT COUNT() FROM AsyncApexJob WHERE JobType = 'BatchApex'],
      'Expected recipient-scoped digest batch to run.'
    );
  }

  @IsTest
  static void batchExecuteProcessesActiveDigestRules() {
    NotificationCenterEventPublisher.resetForTest();
    NotificationTestDataFactory.NotificationTestContext context = NotificationTestDataFactory.createHouseholdWithRecipient();
    Notification_Rule__c rule = NotificationTestDataFactory.createUserPreference(
      NotificationConstants.OBJECT_TYPE_CASE,
      context.recipientUser.Id,
      NotificationConstants.CHANNEL_EMAIL,
      NotificationConstants.FREQUENCY_DIGEST
    );
    rule.Digest_Cadence__c = NotificationConstants.DIGEST_FREQUENCY_DAILY;
    rule.Digest_Frequency_Hour__c = NotificationDigestTimezoneService.currentDigestHourValue();
    NotificationTestDataFactory.updateRecord(rule);

    Test.startTest();
    Database.executeBatch(
      new NotificationDigestRuleBatch(NotificationConstants.DIGEST_FREQUENCY_DAILY),
      200
    );
    Test.stopTest();

    System.assert(true, 'Digest rule batch should process active digest rules.');
  }

  @IsTest
  static void executeLogScopePublishesDigestDeliveryGroups() {
    NotificationCenterEventPublisher.resetForTest();

    NotificationTestDataFactory.NotificationTestContext context = NotificationTestDataFactory.createHouseholdWithRecipient();
    Case caseRecord = createOwnedCase(context);
    Notification_Log__c logRecord = createDigestInAppLog(context, caseRecord.Id);

    NotificationDigestRuleBatch batch = new NotificationDigestRuleBatch(
      NotificationConstants.DIGEST_FREQUENCY_DAILY,
      null,
      null,
      null,
      new List<Id>{ logRecord.Id },
      NotificationConstants.CHANNEL_IN_APP,
      new NotificationDigestRepository()
    );

    List<Notification_Log__c> scope = [
      SELECT
        Id,
        Name,
        Recipient__c,
        Channel__c,
        Source_Type__c,
        Notification_Rule__c,
        Title__c,
        Body__c,
        Change_Context__c,
        CreatedDate,
        Source_Record_Id__c,
        Target_Record_Id__c,
        Household__c,
        Status__c,
        Frequency__c,
        Delivery_Attempt_Count__c
      FROM Notification_Log__c
      WHERE Id = :logRecord.Id
    ];

    batch.execute(null, scope);

    System.assert(
      NotificationCenterEventPublisher.testPublishedEventCount > 0,
      'Log-scoped execute should publish digest delivery groups.'
    );
  }

  @IsTest
  static void executeReturnsEarlyForEmptyScope() {
    NotificationDigestRuleBatch batch = new NotificationDigestRuleBatch(
      NotificationConstants.DIGEST_FREQUENCY_DAILY
    );

    batch.execute(null, new List<Notification_Log__c>());
    batch.execute(null, null);

    System.assert(true, 'Empty batch scope should return without errors.');
  }

  private static Case createOwnedCase(
    NotificationTestDataFactory.NotificationTestContext context
  ) {
    Case caseRecord = new Case(
      Subject = 'Digest batch case',
      AccountId = context.household.Id,
      OwnerId = context.recipientUser.Id
    );
    NotificationTestDataFactory.insertRecord(caseRecord);
    return caseRecord;
  }

  private static Notification_Log__c createDigestInAppLog(
    NotificationTestDataFactory.NotificationTestContext context,
    Id sourceRecordId
  ) {
    Notification_Rule__c rule = NotificationTestDataFactory.createUserPreference(
      NotificationConstants.OBJECT_TYPE_CASE,
      context.recipientUser.Id,
      NotificationConstants.CHANNEL_IN_APP,
      NotificationConstants.FREQUENCY_DIGEST
    );
    rule.Digest_Cadence__c = NotificationConstants.DIGEST_FREQUENCY_DAILY;
    rule.Digest_Frequency_Hour__c = NotificationDigestTimezoneService.currentDigestHourValue();
    NotificationTestDataFactory.updateRecord(rule);

    Notification_Log__c logRecord = NotificationTestDataFactory.createLogNotification(
      context.recipientUser.Id,
      context.household.Id,
      NotificationConstants.OBJECT_TYPE_CASE,
      NotificationConstants.STATUS_QUEUED,
      NotificationConstants.CHANNEL_IN_APP,
      NotificationConstants.FREQUENCY_DIGEST,
      'Digest in-app item',
      null,
      rule.Id
    );
    logRecord.Source_Record_Id__c = String.valueOf(sourceRecordId);
    NotificationTestDataFactory.updateRecord(logRecord);
    return logRecord;
  }
}