unpackaged/main/default/objects/Financial_Account_Related_Product__c/Financial_Account_Related_Product__c.object-meta.xml
<CustomObject>
    <label>Related Product</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Related Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Account_Related_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Related Products</relationshipLabel>
    <relationshipName>Financial_Account_Product1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

unpackaged/main/default/objects/Financial_Account_Related_Product__c/fields/Wizard_Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Related Products</relationshipLabel>
    <relationshipName>Related_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/Flow_createFARPs_Test.cls
@istest
public class Flow_createFARPs_Test {
	/*@istest
    static void createFARPstest(){
        Flow_CreateFARPs.FlowInput flowInput=new Flow_CreateFARPs.FlowInput();
        List<Flow_CreateFARPs.FlowInput> flowInputList=new List<Flow_CreateFARPs.FlowInput>();
        List<Flow_CreateFARPs.FlowOutput> flowOutputList=new List<Flow_CreateFARPs.FlowOutput>();
        
        List<Wizard_Financial_Account__c> inputs=new List<Wizard_Financial_Account__c>();
        List<String> prodIds = new List<String>();
        Wizard_Financial_Account__c wizFin = new Wizard_Financial_Account__c();
        insert wizFin;
        inputs.add(wizFin);
        flowInput.finAccts=inputs;
        Product__c prod = new Product__c();
        insert prod;
        prodIds.add(prod.Id);
        flowInput.productIds=prodIds;
        flowInput.interviewId = 'test';
  		flowInputList.add(flowInput);       
        test.startTest();
        flowOutputList=Flow_CreateFARPs.createFARPs(flowInputList);
        test.stopTest();
       // boolean b=flowOutputList[0].collRemoved.contains('One');
        system.assertEquals(flowOutputList[0].count == 1, true);
        List<Financial_Account_Related_Product__c> farps = [SELECT Id FROM Financial_Account_Related_Product__c];
        delete farps;
        
    }*/
    
}