unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team__c/fields/Public_Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Public_Group_ID__c</fullName>
    <label>Public Group ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/Financial_Advisor_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team Member</label>
    <nameField>
        <displayFormat>FATM-{0000}</displayFormat>
        <label>Financial Advisor Team Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Advisor Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Financial Advisor Team Members</relationshipLabel>
    <relationshipName>Financial_Advisor_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/Group_Member_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Member_Id__c</fullName>
    <label>Group Member Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Financial_Advisor_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/UpdateFATMemberAfterGroupMemberQueue.cls
public class UpdateFATMemberAfterGroupMemberQueue implements Queueable {
    
    private Map<String,Id> groupIdWithUserIdMap;
    private List<Financial_Advisor_Team_Member__c> newList;
    private Map<Id, Financial_Advisor_Team__c> fATeamMap;
    
    public UpdateFATMemberAfterGroupMemberQueue(Map<String,Id> groupIdWithUserIdMap, List<Financial_Advisor_Team_Member__c> newList, Map<Id, Financial_Advisor_Team__c> fATeamMap) {
        this.groupIdWithUserIdMap = groupIdWithUserIdMap;
        this.newList = newList;
        this.fATeamMap = fATeamMap;
    }
    public void execute(QueueableContext context) {
        try {
            List<GroupMember> groupMemberList = [Select id, groupId, UserOrGroupId From  GroupMember Where 
                                                 groupId IN: groupIdWithUserIdMap.keySet() 
                                                 AND UserOrGroupId IN :groupIdWithUserIdMap.values()];
            List<Financial_Advisor_Team_Member__c> fATMemberToUpdateList = new List<Financial_Advisor_Team_Member__c>();
            for(Financial_Advisor_Team_Member__c fAdvisorTeamMember : newList) {
                for(GroupMember  gMember : groupMemberList){
                    if(fATeamMap.get(fAdvisorTeamMember.Financial_Advisor_Team__c).Public_Group_Id__c == gMember.groupId
                       && fAdvisorTeamMember.User__c ==  gMember.UserOrGroupId){
                           Financial_Advisor_Team_Member__c fatM = new Financial_Advisor_Team_Member__c(Id = fAdvisorTeamMember.Id);
                           fatM.Group_Member_Id__c = gMember.Id;
                           fATMemberToUpdateList.add(fatM);
                       }
                }
            }
            update fATMemberToUpdateList;
        } catch(Exception ex){
            System.debug('UpdateFATMemberAfterGroupMemberQueue exception at line No.: '+ex.getLineNumber() + ' '+ex.getMessage());
        }
    }
}