unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/Financial_Advisor_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team Member</label>
    <nameField>
        <displayFormat>FATM-{0000}</displayFormat>
        <label>Financial Advisor Team Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Advisor Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Financial Advisor Team Members</relationshipLabel>
    <relationshipName>Financial_Advisor_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/CreateGroupMemberQueue.cls
public class CreateGroupMemberQueue implements Queueable {
    
    private Map<String,Id> groupIdWithUserIdMap;
    private List<Financial_Advisor_Team_Member__c> newList;
    private Map<Id, Financial_Advisor_Team__c> fATeamMap;
    
    public CreateGroupMemberQueue(Map<String,Id> groupIdWithUserIdMap, List<Financial_Advisor_Team_Member__c> newList, Map<Id, Financial_Advisor_Team__c> fATeamMap) {
        this.groupIdWithUserIdMap = groupIdWithUserIdMap;
        this.newList = newList;
        this.fATeamMap = fATeamMap;
        
    }
    public void execute(QueueableContext context) {
        try {
            List<GroupMember> groupMemberToBeInsertList = new List<GroupMember>();
            system.debug('groupIdWithUserIdMap  :'+groupIdWithUserIdMap);
            for(String groupId : groupIdWithUserIdMap.keyset()){
                GroupMember groupMemberRecord = new GroupMember();
                groupMemberRecord.groupId = Id.valueOf(groupId);
                groupMemberRecord.UserOrGroupId = groupIdWithUserIdMap.get(groupId);
                groupMemberToBeInsertList.add(groupMemberRecord);
            }
            system.debug('groupMemberToBeInsertList  :'+groupMemberToBeInsertList);
            insert groupMemberToBeInsertList;
            if(!Test.isRunningTest()){
                System.enqueueJob(new UpdateFATMemberAfterGroupMemberQueue(groupIdWithUserIdMap, newList, fATeamMap));
            }
        } catch(Exception ex){
            System.debug('CreateGroupMemberQueue exception at line No.: '+ex.getLineNumber() + ' '+ex.getMessage());
        }
    }
}