unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team__c/fields/Registered_States__c.field-meta.xml
<CustomField>
    <fullName>Registered_States__c</fullName>
    <label>Registered States</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/Financial_Advisor_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team Member</label>
    <nameField>
        <displayFormat>FATM-{0000}</displayFormat>
        <label>Financial Advisor Team Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Advisor Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/Employment_Status__c.field-meta.xml
<CustomField>
    <fullName>Employment_Status__c</fullName>
    <label>Employment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>W2 Employee</fullName>
            </value>
            <value>
                <fullName>1099 Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Financial Advisor Team Members</relationshipLabel>
    <relationshipName>Financial_Advisor_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Financial_Advisor_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/User_SSN__c.field-meta.xml
<CustomField>
    <fullName>User_SSN__c</fullName>
    <label>User SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Advisor_SSN__c.field-meta.xml
<CustomField>
    <fullName>Advisor_SSN__c</fullName>
    <label>Advisor SSN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/User_TriggerHandlerTest.cls
@isTest
private class User_TriggerHandlerTest {
    
    @testSetup
    public static void setup(){
        User usr = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            FirstName = 'Test',
            LastName = 'User',
            Email = 'test@email01.com',
            Username = 'user@test.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert usr;
    }
    
    @isTest
    private static void positiveDataInsert() {
        
        Financial_Advisor_Team__c record = new Financial_Advisor_Team__c(Name = 'Test FAT');
        insert record;
        Financial_Advisor_Team__c record2 = new Financial_Advisor_Team__c(Name = 'Default Team');
        insert record2;

        Financial_Advisor_Team_Member__c fatMemberRec = new Financial_Advisor_Team_Member__c(Active__c = true, Financial_Advisor_Team__c = record.Id,
                                                                 Employment_Status__c = 'W2 Employee', User_SSN__c = '12345');
        insert fatMemberRec;
        
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        String orgId = UserInfo.getOrganizationId();
        
        Test.startTest();
        User testUser = new User(Firstname = 'Test FirstName', lastName = 'Test LastName', Email = 'TestFirstName' + '@test' + orgId + '.org',
                                 Username = 'TestFirstName' + '@test' + orgId + '.org', EmailEncodingKey = 'ISO-8859-1',
                                 Alias = 'Test', TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',
                                 LanguageLocaleKey = 'en_US', ProfileId = pf.Id, Advisor_SSN__c = '12345');
        insert testUser;
        Test.stopTest();
        
        List<Financial_Advisor_Team_Member__c> fatmUpdate = [SELECT Id, User__c, Name, User_SSN__c FROM Financial_Advisor_Team_Member__c];
        Assert.areEqual(testUser.Id, fatmUpdate[0].User__c, 'User field should be updated according to User SSN Matching');
        update testUser;
    }
    
    @isTest
    private static void testAfterUpdate(){
        Financial_Advisor_Team__c record = new Financial_Advisor_Team__c(Name = 'Test FAT');
        insert record;
        Financial_Advisor_Team__c record2 = new Financial_Advisor_Team__c(Name = 'Default Team');
        insert record2;
        
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User user=new User(
            ProfileId=pf.Id,
            LastName='testuser',
            Email='test@email01.com',
            Username='user@test.com'+system.currentTimeMillis(),
            Title='title',
            CompanyName='Test',
            Alias='alias',
            TimeZoneSidKey='America/Los_Angeles',
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            IsActive=true,
            Registered_States__c='test1,test2'
            
        );
        insert user;
        Financial_Advisor_Team_Member__c fatMemberRec = new Financial_Advisor_Team_Member__c(Active__c = true, Financial_Advisor_Team__c = record.Id, User__c=user.Id, Employment_Status__c = 'W2 Employee');
        insert fatMemberRec;
        Test.startTest();
        user.Registered_States__c='test1,test2,test3';
        update user;
        Test.stopTest();
        Assert.areEqual('test1,test2,test3', [SELECT Id, Registered_States__c FROM Financial_Advisor_Team_Member__c][0].Registered_States__c);      
    }
}