unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/Financial_Advisor_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team Member</label>
    <nameField>
        <displayFormat>FATM-{0000}</displayFormat>
        <label>Financial Advisor Team Member #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Advisor Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Financial Advisor Team Members</relationshipLabel>
    <relationshipName>Financial_Advisor_Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Financial_Advisor_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/FinancialAdvisorTeamAccessService.cls
/**
 * Author: Hoang Long Vu To
 * Date: 2026-08-11
 *
 * Resolves Financial Advisor Team membership for the running user.
 */
public with sharing class FinancialAdvisorTeamAccessService {
  public class TeamAccessContext {
    public Set<Id> teamIds { get; private set; }
    public Set<Id> teamMemberUserIds { get; private set; }

    public TeamAccessContext(Set<Id> teamIds, Set<Id> teamMemberUserIds) {
      this.teamIds = teamIds == null ? new Set<Id>() : teamIds;
      this.teamMemberUserIds = teamMemberUserIds == null
        ? new Set<Id>()
        : teamMemberUserIds;
    }
  }

  public TeamAccessContext getCurrentUserTeamAccess() {
    Id currentUserId = UserInfo.getUserId();
    Set<Id> teamIds = new Set<Id>();

    for (Financial_Advisor_Team_Member__c membership : [
      SELECT Financial_Advisor_Team__c
      FROM Financial_Advisor_Team_Member__c
      WHERE User__c = :currentUserId
      WITH SECURITY_ENFORCED
    ]) {
      if (membership.Financial_Advisor_Team__c != null) {
        teamIds.add(membership.Financial_Advisor_Team__c);
      }
    }

    Set<Id> teamMemberUserIds = new Set<Id>{ currentUserId };
    if (!teamIds.isEmpty()) {
      for (Financial_Advisor_Team_Member__c member : [
        SELECT User__c
        FROM Financial_Advisor_Team_Member__c
        WHERE
          Financial_Advisor_Team__c IN :teamIds
          AND User__c != NULL
        WITH SECURITY_ENFORCED
      ]) {
        teamMemberUserIds.add(member.User__c);
      }
    }

    return new TeamAccessContext(teamIds, teamMemberUserIds);
  }
}