unpackaged/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Allocation__c/fields/Advisor_Notes__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Notes__c</fullName>
    <label>Advisor Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Allocation__c/fields/Current_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Current_Allocation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Allocation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Allocation__c/fields/Date_Implemented__c.field-meta.xml
<CustomField>
    <fullName>Date_Implemented__c</fullName>
    <label>Date Implemented</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Allocation__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Allocation__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Allocation__c/fields/Request_Allocation_Originated_From__c.field-meta.xml
<CustomField>
    <fullName>Request_Allocation_Originated_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Allocation Originated From</label>
    <referenceTo>Order_Ticket__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Allocation__c/fields/Wizard_Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Allocation_Strategy__c/Allocation_Strategy__c.object-meta.xml
<CustomObject>
    <label>Allocation Strategy</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Allocation Strategy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Strategies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Allocation_Strategy__c/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <label>Allocation</label>
    <referenceTo>Allocation__c</referenceTo>
    <relationshipLabel>Allocation Strategies</relationshipLabel>
    <relationshipName>Allocation_Strategies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Allocation_Strategy__c/fields/Funding_Basis__c.field-meta.xml
<CustomField>
    <fullName>Funding_Basis__c</fullName>
    <description>Snapshot of Order__c.Funding_Basis__c taken when the Order Ticket completed (see Allocation_TriggerHandler.setAllocationStrategies). Dollar sleeves are fixed carve-outs; Percent sleeves describe the actively traded remainder and total 100% across the allocation. Blank on snapshots taken before this field existed.</description>
    <inlineHelpText>Dollar = fixed amount that does not float with account value. Percent = share of the remainder after fixed-dollar sleeves.</inlineHelpText>
    <label>Funding Basis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Allocation_Strategy__c/fields/Initial_Funding_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Initial_Funding_Percentage__c</fullName>
    <label>Initial Funding Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Allocation_Strategy__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategy</label>
    <referenceTo>Strategy__c</referenceTo>
    <relationshipLabel>Allocation Strategies</relationshipLabel>
    <relationshipName>Allocation_Strategies</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Financial_Account__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipName>Wizard_Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Financial_Advisor_Team__c/Financial_Advisor_Team__c.object-meta.xml
<CustomObject>
    <label>Financial Advisor Team</label>
    <nameField>
        <label>Financial Advisor Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Advisor Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Funding_Basis__c.field-meta.xml
<CustomField>
    <fullName>Funding_Basis__c</fullName>
    <description>How the advisor expressed this sleeve&#39;s allocation. Dollar sleeves are fixed carve-outs that should not float with account value. Percent sleeves describe the actively traded remainder after all Dollar sleeves on the same Order Ticket and must total 100% across the ticket. Blank on rows created before this field existed (treat as Percent of total, the legacy convention).</description>
    <inlineHelpText>Dollar = fixed amount that does not float with account value. Percent = share of the remainder after fixed-dollar sleeves.</inlineHelpText>
    <label>Funding Basis</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Initial_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Funding_Amount__c</fullName>
    <label>Initial Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Order_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Ticket</label>
    <referenceTo>Order_Ticket__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategy</label>
    <referenceTo>Strategy__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Strategy_Code__c.field-meta.xml
<CustomField>
    <fullName>Strategy_Code__c</fullName>
    <label>Strategy Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/Order_Ticket__c.object-meta.xml
<CustomObject>
    <label>Order Ticket</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Order Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Ticket__c/fields/Advisor_Notes__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Notes__c</fullName>
    <label>Advisor Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Financial_Advisor_Team__c.field-meta.xml
<CustomField>
    <fullName>Financial_Advisor_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Advisor Team</label>
    <referenceTo>Financial_Advisor_Team__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/of_Orders__c.field-meta.xml
<CustomField>
    <fullName>of_Orders__c</fullName>
    <label># of Orders</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ops Review</fullName>
            </value>
            <value>
                <fullName>Ops Hold</fullName>
            </value>
            <value>
                <fullName>Ops Complete</fullName>
            </value>
            <value>
                <fullName>Pending Funding</fullName>
            </value>
            <value>
                <fullName>Funded Pending Trading</fullName>
            </value>
            <value>
                <fullName>No E-Delivery</fullName>
            </value>
            <value>
                <fullName>Not Enabled</fullName>
            </value>
            <value>
                <fullName>AM Flagged</fullName>
            </value>
            <value>
                <fullName>OCI Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed-No Action</fullName>
            </value>
            <value>
                <fullName>Closed - Error</fullName>
            </value>
            <value>
                <fullName>Waiting on Trade Instructions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Strategy__c.field-meta.xml
<CustomField>
    <fullName>Strategy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strategy</label>
    <referenceTo>Strategy__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Strategy_Code__c.field-meta.xml
<CustomField>
    <fullName>Strategy_Code__c</fullName>
    <label>Strategy Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Wizard_Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Strategy__c/Strategy__c.object-meta.xml
<CustomObject>
    <label>Strategy</label>
    <nameField>
        <label>Strategy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strategies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Strategy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Strategy__c/fields/Strategy_Code__c.field-meta.xml
<CustomField>
    <fullName>Strategy_Code__c</fullName>
    <label>Strategy Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/Order_Ticket_TriggerHandlerTest.cls
/**
 * Order_Ticket_TriggerHandler: the Completed-transition snapshot. A ticket that first reaches
 * Completed with orders and a wizard Financial Account becomes that account's current
 * Allocation__c; Allocation_TriggerHandler then copies the orders onto it as strategies.
 *
 * Every Funding_Basis__c reference is kept on its own line on purpose:
 * the prod build of this class is derived by dropping each line that names that field
 * (see manifest/order-ticket-allocation).
 */
@isTest
private class Order_Ticket_TriggerHandlerTest {

    @testSetup
    static void setup() {
        // Financial_Advisor_Team_Trigger creates the team public group on insert; the wizard
        // Financial Account carries the team so the allocation can inherit it.
        insert new Financial_Advisor_Team__c(Name = 'OT Test Team');
        Financial_Advisor_Team__c team = [SELECT Id FROM Financial_Advisor_Team__c WHERE Name = 'OT Test Team' LIMIT 1];
        insert new List<Financial_Account__c>{
            new Financial_Account__c(Name = 'OT Wiz FA With Team', Financial_Advisor_Team__c = team.Id),
            new Financial_Account__c(Name = 'OT Wiz FA No Team')
        };
        insert new Strategy__c(Name = 'OT Core Equity', Status__c = 'Active', Strategy_Code__c = 'CE');
    }

    private static Financial_Account__c wizardAccount(String name) {
        return [SELECT Id, Financial_Advisor_Team__c FROM Financial_Account__c WHERE Name = :name LIMIT 1];
    }

    private static Order_Ticket__c newTicket(Id wizardAccountId, Decimal orderCount) {
        return new Order_Ticket__c(
            Status__c = 'New',
            Amount__c = 100,
            of_Orders__c = orderCount,
            Wizard_Financial_Account__c = wizardAccountId,
            Advisor_Notes__c = 'Please allocate'
        );
    }

    private static List<Order__c> ordersFor(Id ticketId) {
        Id strategyId = [SELECT Id FROM Strategy__c WHERE Name = 'OT Core Equity' LIMIT 1].Id;
        return new List<Order__c>{
            new Order__c(
                Order_Ticket__c = ticketId,
                Strategy__c = strategyId,
                Strategy_Code__c = 101,
                Order_Type__c = 'Buy',
                Funding_Basis__c = 'Percent',
                Initial_Funding_Percentage__c = 60
            ),
            new Order__c(
                Order_Ticket__c = ticketId,
                Strategy__c = strategyId,
                Strategy_Code__c = 102,
                Order_Type__c = 'Buy',
                Funding_Basis__c = 'Dollar',
                Initial_Funding_Amount__c = 4000
            )
        };
    }

    private static List<Allocation__c> allocationsFor(Id ticketId) {
        return [
            SELECT Id, Current_Allocation__c, Date_Implemented__c, Wizard_Financial_Account__c,
                   Financial_Advisor_Team__c, Advisor_Notes__c, Request_Allocation_Originated_From__c
            FROM Allocation__c
            WHERE Request_Allocation_Originated_From__c = :ticketId
        ];
    }

    @isTest
    static void completionCreatesCurrentAllocationWithStrategies() {
        Financial_Account__c wizFa = wizardAccount('OT Wiz FA With Team');
        Order_Ticket__c ticket = newTicket(wizFa.Id, 2);
        insert ticket;
        insert ordersFor(ticket.Id);

        Test.startTest();
        ticket.Status__c = 'Completed';
        update ticket;
        Test.stopTest();

        List<Allocation__c> allocs = allocationsFor(ticket.Id);
        Assert.areEqual(1, allocs.size(), 'Completing a ticket with orders creates one allocation.');
        Allocation__c alloc = allocs[0];
        Assert.isTrue(alloc.Current_Allocation__c, 'The new allocation is the current one.');
        Assert.areEqual(Date.today(), alloc.Date_Implemented__c, 'Implemented today.');
        Assert.areEqual(wizFa.Id, alloc.Wizard_Financial_Account__c, 'Keyed on the ticket wizard account.');
        Assert.areEqual(wizFa.Financial_Advisor_Team__c, alloc.Financial_Advisor_Team__c, 'Team inherited from the wizard account.');
        Assert.areEqual('Please allocate', alloc.Advisor_Notes__c, 'Advisor notes carried over.');

        List<Allocation_Strategy__c> strategies = [
            SELECT Strategy_Code__c FROM Allocation_Strategy__c WHERE Allocation__c = :alloc.Id ORDER BY Strategy_Code__c
        ];
        Assert.areEqual(2, strategies.size(), 'Allocation_TriggerHandler copied both orders onto the allocation.');
        Assert.isTrue(strategies[0].Strategy_Code__c == 101, 'First strategy code copied, was ' + strategies[0].Strategy_Code__c);
        Assert.isTrue(strategies[1].Strategy_Code__c == 102, 'Second strategy code copied, was ' + strategies[1].Strategy_Code__c);
    }

    @isTest
    static void accountWithoutTeamStillGetsAllocation() {
        Financial_Account__c wizFa = wizardAccount('OT Wiz FA No Team');
        Order_Ticket__c ticket = newTicket(wizFa.Id, 1);
        insert ticket;
        insert new Order__c(Order_Ticket__c = ticket.Id, Strategy_Code__c = 103, Initial_Funding_Percentage__c = 100);

        Test.startTest();
        ticket.Status__c = 'Completed';
        update ticket;
        Test.stopTest();

        List<Allocation__c> allocs = allocationsFor(ticket.Id);
        Assert.areEqual(1, allocs.size(), 'A teamless wizard account still gets its allocation.');
        Assert.isNull(allocs[0].Financial_Advisor_Team__c, 'No team to inherit.');
    }

    @isTest
    static void noOrdersMeansNoAllocation() {
        Financial_Account__c wizFa = wizardAccount('OT Wiz FA With Team');
        Order_Ticket__c zeroOrders = newTicket(wizFa.Id, 0);
        Order_Ticket__c nullOrders = newTicket(wizFa.Id, null);
        insert new List<Order_Ticket__c>{ zeroOrders, nullOrders };

        Test.startTest();
        zeroOrders.Status__c = 'Completed';
        nullOrders.Status__c = 'Completed';
        update new List<Order_Ticket__c>{ zeroOrders, nullOrders };
        Test.stopTest();

        Assert.areEqual(0, allocationsFor(zeroOrders.Id).size(), 'Zero orders: no allocation.');
        Assert.areEqual(0, allocationsFor(nullOrders.Id).size(), 'Blank order count: no allocation.');
    }

    @isTest
    static void noWizardAccountMeansNoAllocationAndNoError() {
        Order_Ticket__c ticket = newTicket(null, 1);
        insert ticket;
        insert new Order__c(Order_Ticket__c = ticket.Id, Strategy_Code__c = 104, Initial_Funding_Percentage__c = 100);

        Test.startTest();
        ticket.Status__c = 'Completed';
        update ticket;   // used to throw a NullPointerException out of the trigger
        Test.stopTest();

        Assert.areEqual('Completed', [SELECT Status__c FROM Order_Ticket__c WHERE Id = :ticket.Id].Status__c,
            'The ticket still completes.');
        Assert.areEqual(0, allocationsFor(ticket.Id).size(), 'Nothing to key the allocation on, so none is created.');
    }

    @isTest
    static void onlyTheTransitionIntoCompletedCreatesAnAllocation() {
        Financial_Account__c wizFa = wizardAccount('OT Wiz FA With Team');
        Order_Ticket__c ticket = newTicket(wizFa.Id, 1);
        insert ticket;
        insert new Order__c(Order_Ticket__c = ticket.Id, Strategy_Code__c = 105, Initial_Funding_Percentage__c = 100);

        Test.startTest();
        ticket.Status__c = 'Ops Review';
        update ticket;
        Assert.areEqual(0, allocationsFor(ticket.Id).size(), 'Moving to a non-Completed status creates nothing.');

        ticket.Status__c = 'Completed';
        update ticket;
        Assert.areEqual(1, allocationsFor(ticket.Id).size(), 'First arrival at Completed creates the allocation.');

        ticket.Advisor_Notes__c = 'Edited after completion';
        update ticket;
        Test.stopTest();

        Assert.areEqual(1, allocationsFor(ticket.Id).size(), 'Editing an already-Completed ticket does not add another.');
    }

    @isTest
    static void bulkUpdateOnlyAllocatesQualifyingTickets() {
        Financial_Account__c wizFa = wizardAccount('OT Wiz FA With Team');
        Order_Ticket__c qualifying = newTicket(wizFa.Id, 1);
        Order_Ticket__c noOrders = newTicket(wizFa.Id, 0);
        Order_Ticket__c noAccount = newTicket(null, 1);
        Order_Ticket__c staysOpen = newTicket(wizFa.Id, 1);
        List<Order_Ticket__c> tickets = new List<Order_Ticket__c>{ qualifying, noOrders, noAccount, staysOpen };
        insert tickets;
        insert new List<Order__c>{
            new Order__c(Order_Ticket__c = qualifying.Id, Strategy_Code__c = 106, Initial_Funding_Percentage__c = 100),
            new Order__c(Order_Ticket__c = noAccount.Id, Strategy_Code__c = 107, Initial_Funding_Percentage__c = 100),
            new Order__c(Order_Ticket__c = staysOpen.Id, Strategy_Code__c = 108, Initial_Funding_Percentage__c = 100)
        };

        Test.startTest();
        qualifying.Status__c = 'Completed';
        noOrders.Status__c = 'Completed';
        noAccount.Status__c = 'Completed';
        staysOpen.Status__c = 'Ops Complete';
        update tickets;
        Test.stopTest();

        Assert.areEqual(1, allocationsFor(qualifying.Id).size(), 'Only the qualifying ticket allocates.');
        Assert.areEqual(0, allocationsFor(noOrders.Id).size());
        Assert.areEqual(0, allocationsFor(noAccount.Id).size());
        Assert.areEqual(0, allocationsFor(staysOpen.Id).size());
        Assert.areEqual(1, [SELECT COUNT() FROM Allocation__c], 'Exactly one allocation across the whole batch.');
    }

    @isTest
    static void deleteAndUndeleteRunTheEmptyHandlers() {
        Order_Ticket__c ticket = newTicket(null, 0);
        insert ticket;

        Test.startTest();
        delete ticket;
        undelete ticket;
        Test.stopTest();

        Assert.areEqual(1, [SELECT COUNT() FROM Order_Ticket__c WHERE Id = :ticket.Id], 'Ticket restored.');
    }
}