unpackaged/main/default/objects/Advertising_Item__c/Advertising_Item__c.object-meta.xml
<CustomObject>
    <label>Advertising Item</label>
    <nameField>
        <label>Advertising Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertising Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advertising_Item__c/fields/Advertising_Type__c.field-meta.xml
<CustomField>
    <fullName>Advertising_Type__c</fullName>
    <label>Advertising Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brochure/Worksheet/Pamphlet</fullName>
            </value>
            <value>
                <fullName>Business Card</fullName>
            </value>
            <value>
                <fullName>Business Envelope</fullName>
            </value>
            <value>
                <fullName>Email Signature</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Fax Coversheet</fullName>
            </value>
            <value>
                <fullName>Form Letter</fullName>
            </value>
            <value>
                <fullName>Group Email</fullName>
            </value>
            <value>
                <fullName>Letterhead</fullName>
            </value>
            <value>
                <fullName>Newsletter/Circular</fullName>
            </value>
            <value>
                <fullName>Periodical Print/Reprint</fullName>
            </value>
            <value>
                <fullName>Postcard</fullName>
            </value>
            <value>
                <fullName>Presentation</fullName>
            </value>
            <value>
                <fullName>Press Release</fullName>
            </value>
            <value>
                <fullName>Public Appearance</fullName>
            </value>
            <value>
                <fullName>Radio/TV Ad</fullName>
            </value>
            <value>
                <fullName>Seminar Handout</fullName>
            </value>
            <value>
                <fullName>Social Media Content</fullName>
            </value>
            <value>
                <fullName>Social Media Profile</fullName>
            </value>
            <value>
                <fullName>Sponsorship</fullName>
            </value>
            <value>
                <fullName>Video/Audio</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>FINRA Review</fullName>
                <isActive>false</isActive>
                <label>FINRA Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Allocation__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Allocation__c/fields/Request_Allocation_Originated_From__c.field-meta.xml
<CustomField>
    <fullName>Request_Allocation_Originated_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request Allocation Originated From</label>
    <referenceTo>Order_Ticket__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Allocation__c/fields/Wizard_Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Allocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Allocation_Strategy__c/Allocation_Strategy__c.object-meta.xml
<CustomObject>
    <label>Allocation Strategy</label>
    <nameField>
        <displayFormat>AS-{00000000}</displayFormat>
        <label>Allocation Strategy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocation Strategies</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Allocation_Strategy__c/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <label>Allocation</label>
    <referenceTo>Allocation__c</referenceTo>
    <relationshipLabel>Allocation Strategies</relationshipLabel>
    <relationshipName>Allocation_Strategies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Allocation_Strategy__c/fields/Initial_Funding_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Initial_Funding_Percentage__c</fullName>
    <label>Initial Funding Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

unpackaged/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order__c/fields/Initial_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Initial_Funding_Amount__c</fullName>
    <label>Initial Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Order__c/fields/Order_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Order_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Ticket</label>
    <referenceTo>Order_Ticket__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/Order_Ticket__c.object-meta.xml
<CustomObject>
    <label>Order Ticket</label>
    <nameField>
        <displayFormat>OT-{00000}</displayFormat>
        <label>Order Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Order_Ticket__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>FinServ__FinancialAccount__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Flow_Interview_ID__c.field-meta.xml
<CustomField>
    <fullName>Flow_Interview_ID__c</fullName>
    <label>Flow Interview ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Ticket__c/fields/Wizard_Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Wizard_Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Order Tickets</relationshipLabel>
    <relationshipName>Order_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/NewAllocationCreateMultiple_Test.cls
@isTest
public class NewAllocationCreateMultiple_Test {

    @testSetup
    public static void setup(){
        // create person account
        Account acc = new Account(FirstName = 'Test', LastName='Account');
        insert acc;
        
        Contact con1 = [SELECT Id FROM Contact WHERE AccountId =: acc.Id];  
        
        List<FinServ__FinancialAccount__c> finAccs = new List<FinServ__FinancialAccount__c>();
        finAccs.add(new FinServ__FinancialAccount__c(Name = 'Test FA1',
                                                     FinServ__PrimaryOwner__c = acc.Id));
        finAccs.add(new FinServ__FinancialAccount__c(Name = 'Test FA2',
                                                     FinServ__PrimaryOwner__c = acc.Id));
        insert finAccs;
        
        
        
        
        
        List<Advertising_Item__c> adItemsList = new List<Advertising_Item__c>();
        adItemsList.add(new Advertising_Item__c(Flow_Interview_ID__c = 'testFlowInt132', Advertising_Type__c = 'Social Media Profile'));
        adItemsList.add(new Advertising_Item__c(Flow_Interview_ID__c = 'testFlowInt234', Advertising_Type__c = 'Social Media Content'));        
        insert adItemsList;
    }
    
    @isTest
    private static void getFieldAndDatatypeTest(){
        String sobjectName = 'Account';
        List<String> sObjectFields = new List<String>{'FirstName', 'LastName' , 'Salutation'};
            Test.startTest();
        List<NewAllocationCreateMultipleController.FieldObj> headerList = NewAllocationCreateMultipleController.getFieldAndDatatype(sobjectName,sObjectFields,null);
        Test.stopTest();
        Assert.isTrue(headerList.size() > 0, 'Method should return list.');
    }
    
    @isTest
    private static void getPicklistOptionsTest(){
        String sobjectName = 'Account';
        String sObjectField = 'Salutation';
        Test.startTest();
        List<String> picklistOptions = NewAllocationCreateMultipleController.getPicklistOptions(sobjectName,sObjectField);
        Test.stopTest();
        Assert.isTrue(picklistOptions.size() > 0, 'Method should return list.');
    }
    
    @isTest
    private static void getExistingRecordsTest(){
        
        List<FinServ__FinancialAccount__c> finAccs = [SELECT Id FROM FinServ__FinancialAccount__c ORDER BY Name Desc];
        Id wizFinId1 = [SELECT Wizard_Financial_Account__c FROM FinServ__FinancialAccount__c WHERE Name = 'Test FA1' LIMIT 1].Wizard_Financial_Account__c;
        System.debug('wizFinId 1: ' + wizFinId1);
        Id wizFinId2 = [SELECT Wizard_Financial_Account__c FROM FinServ__FinancialAccount__c WHERE Name = 'Test FA2' LIMIT 1].Wizard_Financial_Account__c;

        
        List<Order_Ticket__c> ot2List = new List<Order_Ticket__c>();
        ot2List.add(new Order_Ticket__c(Initial_Funding_Percentage__c = 40.5, Amount__c = 40.5, Financial_Account__c = finAccs[0].Id, Wizard_Financial_Account__c = wizFinId1));
        ot2List.add(new Order_Ticket__c(Initial_Funding_Percentage__c = 30, Amount__c = 30, Financial_Account__c = finAccs[1].Id, Wizard_Financial_Account__c = wizFinId2));
        insert ot2List;
        
        System.debug('ot2List: ' + ot2List);
        
        List<Order__c> oList = new List<Order__c>();
        oList.add(new Order__c(Order_Ticket__c = ot2List[0].Id));
        oList.add(new Order__c(Order_Ticket__c = ot2List[1].Id));
        insert oList;
        
        Allocation__c alloc = new Allocation__c(Request_Allocation_Originated_From__c = ot2List[0].Id);
        insert alloc;
        
        List<Allocation_Strategy__c> otList = new List<Allocation_Strategy__c>();
        otList.add(new Allocation_Strategy__c(Initial_Funding_Percentage__c = 40.5, Initial_Funding_Amount__c = 40.5, Allocation__c = alloc.Id));
        otList.add(new Allocation_Strategy__c(Initial_Funding_Percentage__c = 30, Initial_Funding_Amount__c  = 30, Allocation__c = alloc.Id));
        insert otList;
        
        String sobjectName = 'FinServ__FinancialAccount__c';
        String parentRecordId = [SELECT Id FROM Allocation__c Limit 1].Id;
        String wizFinId = [SELECT Wizard_Financial_Account__c FROM FinServ__FinancialAccount__c WHERE Name = 'Test FA1' LIMIT 1].Wizard_Financial_Account__c;
        String parentLookup = 'FinServ__PrimaryOwner__c' ;
        List<String> sObjectFields = new List<String>{'Strategy_Name__c', 'Initial_Funding_Percentage__c'};
            Test.startTest();
        List<SObject> lstRecords = NewAllocationCreateMultipleController.getExistingRecordsToCreateNew(parentRecordId,wizFinId,parentLookup,sObjectFields,null);
        Test.stopTest();
        Assert.isTrue(lstRecords.size() > 0, 'Method should return list.');
    }
    
    @isTest
    private static void upsertRecordTest(){
        List<FinServ__FinancialAccount__c> finAccs = [SELECT Id FROM FinServ__FinancialAccount__c ORDER BY Name Desc];
        Id wizFinId1 = [SELECT Wizard_Financial_Account__c FROM FinServ__FinancialAccount__c WHERE Name = 'Test FA1' LIMIT 1].Wizard_Financial_Account__c;
        System.debug('wizFinId 1: ' + wizFinId1);
        Id wizFinId2 = [SELECT Wizard_Financial_Account__c FROM FinServ__FinancialAccount__c WHERE Name = 'Test FA2' LIMIT 1].Wizard_Financial_Account__c;

        
        List<Order_Ticket__c> ot2List = new List<Order_Ticket__c>();
        ot2List.add(new Order_Ticket__c(Initial_Funding_Percentage__c = 40.5, Amount__c = 40.5, Financial_Account__c = finAccs[0].Id, Wizard_Financial_Account__c = wizFinId1));
        ot2List.add(new Order_Ticket__c(Initial_Funding_Percentage__c = 30, Amount__c = 30, Financial_Account__c = finAccs[1].Id, Wizard_Financial_Account__c = wizFinId2));
        insert ot2List;
        
        List<Order__c> oList = new List<Order__c>();
        oList.add(new Order__c(Order_Ticket__c = ot2List[0].Id));
        oList.add(new Order__c(Order_Ticket__c = ot2List[1].Id));
        insert oList;
        
        Allocation__c alloc = new Allocation__c(Request_Allocation_Originated_From__c = ot2List[0].Id);
        insert alloc;
        
        List<Allocation_Strategy__c> otList = new List<Allocation_Strategy__c>();
        otList.add(new Allocation_Strategy__c(Initial_Funding_Percentage__c = 40.5, Initial_Funding_Amount__c = 40.5, Allocation__c = alloc.Id));
        otList.add(new Allocation_Strategy__c(Initial_Funding_Percentage__c = 30, Initial_Funding_Amount__c  = 30, Allocation__c = alloc.Id));
        insert otList;
        
        String sobjectName = 'Account';
        Map<String, String> recordValues = new Map<String, String>();
        String parentRecordId = [SELECT Id FROM Allocation__c Limit 1].Id;
        String wizFinId = [SELECT Wizard_Financial_Account__c FROM FinServ__FinancialAccount__c WHERE Name = 'Test FA1' LIMIT 1].Wizard_Financial_Account__c;
        recordValues.put('Name' , 'Testing');
        recordValues.put('IsDeleted' , 'false');
        recordValues.put('Salutation' , 'Mr');
        Test.startTest();
        SObject returnedSObjectRecord = NewAllocationCreateMultipleController.upsertRecordForCurrentAllocation(recordValues,parentRecordId,wizFinId);
        Test.stopTest();
        List<Account> accsAfterUpsert = [SELECT Id, Name FROM Account];
        Assert.isTrue(returnedSObjectRecord != Null, 'Method should return a value.');
        Assert.areEqual(1, accsAfterUpsert.size());
    }
    
    
    @isTest
    private static void getTotalFieldSumBLSTCMTest(){
        List<FinServ__FinancialAccount__c> finAccs = [SELECT Id FROM FinServ__FinancialAccount__c ORDER BY Name Desc];
        Id wizFinId1 = [SELECT Wizard_Financial_Account__c FROM FinServ__FinancialAccount__c WHERE Name = 'Test FA1' LIMIT 1].Wizard_Financial_Account__c;
        System.debug('wizFinId 1: ' + wizFinId1);
        Id wizFinId2 = [SELECT Wizard_Financial_Account__c FROM FinServ__FinancialAccount__c WHERE Name = 'Test FA2' LIMIT 1].Wizard_Financial_Account__c;

        
        List<Order_Ticket__c> ot2List = new List<Order_Ticket__c>();
        ot2List.add(new Order_Ticket__c(Initial_Funding_Percentage__c = 40.5, Amount__c = 40.5, Financial_Account__c = finAccs[0].Id, Wizard_Financial_Account__c = wizFinId1));
        ot2List.add(new Order_Ticket__c(Initial_Funding_Percentage__c = 30, Amount__c = 30, Financial_Account__c = finAccs[1].Id, Wizard_Financial_Account__c = wizFinId2));
        insert ot2List;
        
        System.debug('ot2List: ' + ot2List);
        
        List<Order__c> oList = new List<Order__c>();
        oList.add(new Order__c(Order_Ticket__c = ot2List[0].Id));
        oList.add(new Order__c(Order_Ticket__c = ot2List[1].Id));
        insert oList;
        
        Allocation__c alloc = new Allocation__c(Request_Allocation_Originated_From__c = ot2List[0].Id);
        insert alloc;
        
        List<Allocation_Strategy__c> otList = new List<Allocation_Strategy__c>();
        otList.add(new Allocation_Strategy__c(Initial_Funding_Percentage__c = 40.5, Initial_Funding_Amount__c = 40.5, Allocation__c = alloc.Id));
        otList.add(new Allocation_Strategy__c(Initial_Funding_Percentage__c = 30, Initial_Funding_Amount__c  = 30, Allocation__c = alloc.Id));
        insert otList;
        Order_Ticket__c o = [SELECT Id FROM Order_Ticket__c ORDER BY CreatedDate desc LIMIT 1];
        Test.startTest();
        NewAllocationCreateMultipleController.SumObj sumObj = NewAllocationCreateMultipleController.getTotalFieldSumBLSTCM(o.Id);
        Test.stopTest();
        System.debug('sumObj.result: ' + sumObj.result);
        //Assert.isTrue(sumObj.result == 70.5);
        
    }
    
    @isTest
    private static void deleteAllocs(){
        List<Order_Ticket__c> ot2List = new List<Order_Ticket__c>();
        ot2List.add(new Order_Ticket__c(Initial_Funding_Percentage__c = 40.5, Amount__c = 40.5));
        ot2List.add(new Order_Ticket__c(Initial_Funding_Percentage__c = 30, Amount__c = 30));
        insert ot2List;

		List<Order__c> oList = new List<Order__c>();
        oList.add(new Order__c(Order_Ticket__c = ot2List[0].Id));
        oList.add(new Order__c(Order_Ticket__c = ot2List[1].Id));
        insert oList;
        
        Allocation__c alloc = new Allocation__c(Request_Allocation_Originated_From__c = ot2List[0].Id);
        insert alloc;
        
        List<Allocation_Strategy__c> otList = new List<Allocation_Strategy__c>();
        otList.add(new Allocation_Strategy__c(Initial_Funding_Percentage__c = 40.5, Initial_Funding_Amount__c = 40.5, Allocation__c = alloc.Id));
        otList.add(new Allocation_Strategy__c(Initial_Funding_Percentage__c = 30, Initial_Funding_Amount__c  = 30, Allocation__c = alloc.Id));
        insert otList;
        
        Allocation__c alloc2 = [SELECT Id FROM Allocation__c LIMIT 1];
        delete alloc2;
        undelete alloc2;
    }
}