unpackaged/main/default/objects/Advertising_Item__c/Advertising_Item__c.object-meta.xml
<CustomObject>
    <label>Advertising Item</label>
    <nameField>
        <label>Advertising Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertising Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Advertising_Item__c/fields/Date_of_Event__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Event__c</fullName>
    <label>Date of Event</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Advertising_Item__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Appreciation</fullName>
            </value>
            <value>
                <fullName>Retirement</fullName>
            </value>
            <value>
                <fullName>Social Security</fullName>
            </value>
            <value>
                <fullName>Medicare</fullName>
            </value>
            <value>
                <fullName>Accredited Investor Association</fullName>
            </value>
            <value>
                <fullName>General Alternative Investment Education</fullName>
            </value>
            <value>
                <fullName>Private Placement Seminar</fullName>
            </value>
            <value>
                <fullName>Professional Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchEventEmailNotification_Test.cls
@isTest
public class BatchEventEmailNotification_Test {
    
    @testSetup
    public static void setup(){
        User usr = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            FirstName = 'Test',
            LastName = 'User',
            Email = 'test@email01.com',
            Username = 'user@test.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert usr;
        
        System.runAs(usr){
            Advertising_Item__c adItem = new Advertising_Item__c(Name = 'Test Advertisement', Event_Type__c = 'Accredited Investor Association',
                                                                 Date_of_Event__c = Date.today().addDays(-1));
            insert adItem;
        }
    }
    
    @isTest
    public static void testBatch(){
        Test.startTest();
        BatchEventEmailNotification batch = new BatchEventEmailNotification();
        String sch = '0 0 2 * * ?'; 
        String jobId = System.schedule('Test Batch', sch, batch); 
        Test.stopTest();
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        Assert.isNotNull(ct);
        Assert.areEqual(sch, ct.CronExpression);
    }
}