unpackaged/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <label>Announcement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Announcement__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Announcement__c/fields/Link_URL__c.field-meta.xml
<CustomField>
    <fullName>Link_URL__c</fullName>
    <label>Link URL</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Announcement__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ArcAnnouncementController.cls
/**
 * Aura-enabled facade for arcAnnouncements: returns active Announcement__c
 * records, ordered for the banner's prev/next pager.
 */
public with sharing class ArcAnnouncementController {
  @AuraEnabled(cacheable=true)
  public static List<ArcAnnouncementModels.AnnouncementItem> getActiveAnnouncements() {
    List<ArcAnnouncementModels.AnnouncementItem> items = new List<ArcAnnouncementModels.AnnouncementItem>();

    for (Announcement__c announcement : [
      SELECT Id, Name, Body__c, Link_URL__c
      FROM Announcement__c
      WHERE Is_Active__c = TRUE
      WITH SECURITY_ENFORCED
      ORDER BY Sort_Order__c NULLS LAST, CreatedDate DESC
    ]) {
      ArcAnnouncementModels.AnnouncementItem item = new ArcAnnouncementModels.AnnouncementItem();
      item.id = announcement.Id;
      item.title = announcement.Name;
      item.body = announcement.Body__c;
      item.linkUrl = announcement.Link_URL__c;
      items.add(item);
    }

    return items;
  }
}